export class AppCostants {
     
    public static INFO_APPALTI='INFO_APPALTI';
    public static FROM_PORTALE='FROM_PORTALE';
    public static FROM_APPALTI='FROM_APPALTI';
    public static STORE_LANG='LANG';
    public static STORE_OBJ='ALL_DATA';
    public static STORE_USR='USER_INFO';
    public static EO_COMPILE='EO_COMPILE';
    public static SA_COMPILE='SA_COMPILE';
    public static EO='eo';
    public static SA='sa';
    public static EO_IMPORT='eo_import_espd';
    public static SA_IMPORT='sa_import_espd';
    public static EO_JSON='eo_json';
    public static SA_JSON='sa_json';
    public static IMPORT_REQUEST='import_request';
    public static IMPORT_RESPONSE='import_reSPONSE';
    public static PAGE_DGUE_PORTALE='dgue-home-portale';
    public static PAGE_DGUE='dgue-home';
    public static PAGE_COOKIES='cookies';
    public static PAGE_CREDITS='credits';
    public static VISIBLE_HIDDEN_FUNCTION='visible-function';

    public static PAGE_PRIVACY='privacy';
    public static PAGE_DISCLAMER='disclaimer';
    public static PAGE_ASSISTENZA='assistenza';

    public static PAGE_CARICA_FILE='caricamento';

    public static PAGE_AVVIO='avvio';
    public static PAGE_PROCEDURA='procedura';
    public static PAGE_ESCLUSIONE='esclusione';
    public static PAGE_SELEZIONE='selezione';
    public static PAGE_FINE='fine';
    public static PAGE_QUADRO_GENERALE='quadro-generale'
    public static PAGE_QUADRO_GENERALE_APPALTI='quadro-generale-appalti'
    public static PAGE_QUADRO_GENERALE_CARICAMENTO='quadro-generale-caricamento'
    public static TYPE_COMBOBOX= 'COMBOBOX';
    public static TYPE_TEXT='TEXT';
    public static LIST_CODE=["paesi","tipoProcedura","tipoMoneta","ruoloOperatoreEconomico","bidType","DocRefContentType","projectType","typeOfRequirements","IndustryClassificationCode","financialRatioType"];
    public static XML_REQUEST='eDGUE-IT_request';
    public static XML_RESPONSE='eDGUE-IT_response';
    public static ERROR_XML='Non è stato possibile leggere correttamente il file caricato. Controllare che l\'estensione sia .xml';
    public static FROM_XML='FROM_XML';
    public static WHO_IMPORTED='WHO_IMPORTED';
    public static IMPORTED_XML='IMPORTED_XML';
    public static MAG_VAT_NUMBER='02066400405';
    public static MAG_NAME='Maggioli Spa';
    public static MAG_COUNTRY='IT';
    public static XML_ARRAY_CODE=["authority.serviceProvider.country","eoSme.currency","criminalConvictions.answer","inserimento1",
                                 "rispostaUe01form",
                                 "inserimentosub1",
                                 "affidabilitasubform",
                                 "rispostaUesub01form",
                                 "inserimento2",
                                 "rispostaUe02form",
                                 "inserimentosub2",
                                 "affidabilitasub2form",
                                 "rispostaUesub02form",
                                 "inserimento3",
                                 "rispostaUe03form",
                                 "inserimentosub3",
                                 "affidabilitasub3form",
                                 "rispostaUesub03form",
                                 "inserimento4",
                                 "rispostaUe04form",
                                 "inserimentosub4",
                                 "affidabilitasub4form",
                                 "rispostaUesub04form",
                                 "inserimento5",
                                 "rispostaUe05form",
                                 "inserimentosub5",
                                 "affidabilitasub5form",
                                 "rispostaUesub05form",
                                 "inserimento6",
                                 "rispostaUe06form",
                                 "inserimentosub6",
                                 "affidabilitasub6form",
                                 "rispostaUesub06form",
                                 "rispostaUe07form",
                                 "inserimentosub7",
                                 "affidabilitasub7form",
                                 "rispostaUesub07form",
                                 "rispostaUesub08form",
                                 "rispostaUesub13form",
                                 "rispostaUesub09form",
                                 "rispostaUesub10form",
                                 "rispostaUesub11form",
                                 "rispostaUesub12form",
                                 "valIndici",
                                 "CommittenteForm",
                                 "committente",
                                 "nomeCommittente",
                                 "committente2",
                                 "nomeCommittente2",
                                 "committente3",
                                 "nomeCommittente3",
                                 "tecnico",
                                 "organismiTecnici",
                                 "tecnico2",
                                 "organismiTecnici2",
                                 "tecnico3",
                                 "dirigenti",
                                 "rispostaUe39form",
                                 "dirigenti2",
                                 "rispostaUe40form",
                                 "rispostaUe41form",
                                 "rispostaUe42form",
                                 "rispostaUe43form",
                                 "rispostaUe44form",
                                 "rispostaUe45form",
                                 "rispostaUe46form"
                                ];
    public static ARRAY_CODE_COMBO_SINO=["IndustryClassificationCode","eoSme.currency","criminalConvictions.answer","tipoProcedura","financialRatioType",
                            "ruoloOperatoreEconomico",
                            "domandaImpresa",
                            "appaltoRis",
                            "iscrittoElenco",
                            "fornireCert",
                            "criteriSelezione",
                            "partecipaAppalto",
                            "soddisfazioneCriteri",
                            "subappaltare",
                            "criminalConvictions.answer",
                            "affidabilita",
                            "criminalConvictions.rispostaUe01",
                            "sezionesub1.rispostaFornitasub",
                            "inserimentosub1-data-group.affidabilitasub",
                            "risarcimentosub01",
                            "risarcimentoForsub01",
                            "provvedimentisub01",
                            "rispostaUesub01",
                            "corruption.rispostaFornita2",
                            "affidabilita2",
                            "corruption.rispostaUe02",
                            "sezionesub2.rispostaFornitasub2",
                            "affidabilitasub2",
                            "risarcimentosub02",
                            "risarcimentoForsub02",
                            "provvedimentisub02",
                            "rispostaUesub02",
                            "fraud.rispostaFornita3",
                            "affidabilita3",
                            "fraud.rispostaUe03",
                            "sezionesub3.rispostaFornitasub3",
                            "affidabilitasub3",
                            "risarcimentosub03",
                            "risarcimentoForsub03",
                            "provvedimentisub03",
                            "rispostaUesub03",
                            "terroristOffences.rispostaFornita4",
                            "affidabilita4",
                            "terroristOffences.rispostaUe04",
                            "sezionesub4.rispostaFornitasub4",
                            "affidabilitasub4",
                            "risarcimentosub04",
                            "risarcimentoForsub04",
                            "provvedimentisub04",
                            "rispostaUesub04",
                            "moneyLaundering.rispostaFornita5",
                            "affidabilita5",
                            "moneyLaundering.rispostaUe05",
                            "sezionesub5.rispostaFornitasub5",
                            "affidabilitasub5",
                            "risarcimentosub05",
                            "risarcimentoForsub05",
                            "provvedimentisub05",
                            "rispostaUesub05",
                            "childLabour.rispostaFornita6",
                            "affidabilita6",
                            "childLabour.rispostaUe06",
                            "sezionesub6.rispostaFornitasub6",
                            "affidabilitasub6",
                            "risarcimentosub06",
                            "risarcimentoForsub06",
                            "provvedimentisub06",
                            "rispostaUesub06",
                            "paymentTaxes.rispostaFornita2_1",
                            "paymentTaxes.rispostaFornita3_1",
                            "paymentTaxes.rispostaFornita3_2",
                            "paymentTaxes.RispostaInottemperanza",
                            "paymentTaxes.rispostaObblighi",
                            "paymentTaxes.vincolante",
                            "paymentTaxes.rispostaInfo",
                            "paymentSocialSecurity.rispostaFornita2_2",
                            "paymentSocialSecurity.RispostaInottemperanza2",
                            "paymentSocialSecurity.rispostaObblighi2",
                            "paymentSocialSecurity.vincolante2",
                            "paymentSocialSecurity.rispostaInfo2",
                            "breachingObligationsEnvironmental.risposta1",
                            "breachingObligationsEnvironmental.risposta2",
                            "breachingObligationsEnvironmental.risposta3",
                            "sezionesub7.risp",
                            "sezionesub7.risp_2",
                            "sezionesub7.risp_3",
                            "breachingObligationsSocial.risposta1_2",
                            "breachingObligationsSocial.risposta2_2",
                            "breachingObligationsSocial.risposta3_2",
                            "sezionesub8.risp2",
                            "breachingObligationsLabour.risposta1_3",
                            "breachingObligationsLabour.risposta2_3",
                            "breachingObligationsLabour.risposta3_3",
                            "sezionesub9.risp3",
                            "bankruptcy.risposta1_4",
                            "bankruptcy.rispostaUe",
                            "sezionesub10.risp4",
                            "sezionesub10.risp4_2",
                            "insolvency.risposta1_5",
                            "insolvency.rispostaUe2",
                            "sezionesub11.risp5",
                            "arrangementWithCreditors.risposta1_6",
                            "arrangementWithCreditors.rispostaUe3",
                            "sezionesub12.risp6",
                            "sezionesub12.risp5_2",
                            "sezionesub12.risp5_3",
                            "sezionesub12.risp5_4",
                            "analogousSituation.risposta1_7",
                            "analogousSituation.rispostaUe4",
                            "sezionesub13.risp7",
                            "assetsAdministeredByLiquidator.risposta1_8",
                            "assetsAdministeredByLiquidator.rispostaUe5",
                            "sezionesub14.risp8",
                            "businessActivitiesSuspended.risposta1_9",
                            "businessActivitiesSuspended.rispostaUe6",
                            "guiltyGrave.risposta1_10",
                            "guiltyGrave.risposta2_4",
                            "guiltyGrave.rispostaUe7",
                            "sezionesub16.risp10",
                            "sezionesub16.risp10_1",
                            "sezionesub16.risp10_2",
                            "sezionesub16.risp10_3",
                            "sezionesub16.rispostaUe07",
                            "agreementsWithOtherEO.risposta1_11",
                            "agreementsWithOtherEO.risposta2_5",
                            "agreementsWithOtherEO.rispostaUe8",
                            "sezionesub17.risp11",
                            "conflictInterest.risposta1_12",
                            "conflictInterest.rispostaUe9",
                            "sezionesub18.risp12",
                            "involvementPreparationProcurement.risposta1_13",
                            "involvementPreparationProcurement.rispostaUe10",
                            "sezionesub19.risp13",
                            "earlyTermination.risposta1_14",
                            "earlyTermination.risposta2_6",
                            "earlyTermination.rispostaUe11",
                            "sezionesub20.risp14",
                            "sezionesub20.risp15",
                            "guiltyMisinterpretation.risposta1_15",
                            "guiltyMisinterpretation.rispostaUe12",
                            "sezionesub21.risp16",
                            "sezionesub21.risp17",
                            "sezionesub21.risp18",
                            "nationalExclusionGrounds.risposta1_16",
                            "nationalExclusionGrounds.risposta2_7",
                            "nationalExclusionGrounds.rispostaUe13",
                            "sezionesub22.rispostaFornitasub7",
                            "affidabilitasub7",
                            "risarcimentosub07",
                            "risarcimentoForsub07",
                            "provvedimentisub07",
                            "sezionesub22.rispostaCombo01",
                            "sezionesub22.rispostaUesub07",
                            "sezionesub22.rispostaCombo02",
                            "sezionesub22.rispostaUesub08",
                            "sezionesub22.rispostaCombo02",
                            "sezionesub22.rispostaUesub07",
                            "sezionesub22.rispostaCombo03",
                            "sezionesub22.rispostaUesub09",
                            "sezionesub22.rispostaCombo04",
                            "sezionesub22.violazione",
                            "sezionesub22.rispostaUesub10",
                            "sezionesub22.rispostaCombo05",
                            "sezionesub22.rispostaUesub11",
                            "sezionesub22.rispostaCombo06",
                            "sezionesub22.denuncia01",
                            "sezionesub22.ricorrenzaCasi",
                            "sezionesub22.rispostaUesub12",
                            "sezionesub22.rispostaCombo07",
                            "sezionesub22.rispostaCombo08",
                            "sezionesub22.rispostaCombo09",
                            "enrolmentProfessionalRegister.risp",
                            "enrolmentProfessionalRegister.exists",
                            "enrolmentProfessionalRegister.rispostaUe14",
                            "sezionesub23.rispostaFornitasub",
                            "enrolmentTradeRegister.risp2",
                            "enrolmentTradeRegister.rispostaUe15",
                            "sezionesub24.rispostaFornitasub2",
                            "serviceContractsAuthorisation.risp3",
                            "serviceContractsAuthorisation.rispostaUe16",
                            "sezionesub25.rispostaFornitasub3",
                            "serviceContractsMembership.risp4",
                            "serviceContractsMembership.rispostaUe17",
                            "sezionesub26.rispostaFornitasub4",
                            "generalYearlyTurnover.rispostaUe18",
                            "averageYearlyTurnover.rispostaUe19",
                            "sezionesub27.rispostaFornitasub5",
                            "specificAverageTurnover.rispostaUe19",
                            "sezionesub28.rispostaFornitasub6",
                            "specificYearlyTurnover.rispostaUe20",
                            "sezionesub29.rispostaFornitasub7",
                            "setupEconomicOperator.rispostaUe21",
                            "financialRatio.rispostaUe22",
                            "sezionesub30.rispostaFornitasub8",
                            "professionalRiskInsurance.impegno",
                            "professionalRiskInsurance.esente",
                            "professionalRiskInsurance.rispostaUe23",
                            "professionalRiskInsurance.rispostaUe24",
                            "confidenziale",
                            "workContractsPerformanceOfWorks.rispostaUe25",
                            "supplyContractsPerformanceOfDeliveries.confidenziale2",
                            "supplyContractsPerformanceOfDeliveries.rispostaUe26",
                            "serviceContractsPerformanceServices.confidenziale3",
                            "serviceContractsPerformanceServices.rispostaUe27",
                            "sezionesub31.rispostaFornitasub9",
                            "rispostaUe28",
                            "rispostaUe29",
                            "sezionesub32.rispostaFornitasub10",
                            "rispostaUe30",
                            "rispostaUe31",
                            "sezionesub33.rispostaFornitasub11",
                            "technicalFacilitiesMeasures.rispostaUe32",
                            "studyResearchFacilities.rispostaUe33",
                            "supplyChainManagement.rispostaUe34",
                            "environmentalManagementFeatures.rispostaUe35",
                            "toolsPlantTechnicalEquipment.rispostaUe36",
                            "rispostaUe37",
                            "allowanceOfChecks.orgEmittenteQua",
                            "allowanceOfChecks.rispostaUe38",
                            "numberManagerialStaff.rispostaUe39",
                            "averageAnnualManpower.rispostaUe40",
                            "subcontractingProportion.rispostaUe41",
                            "sezionesub34.rispostaFornitasub12",
                            "sezionesub34.risp10",
                            "supplyContractsSamplesDescriptionsWithoutCa.risp5",
                            "supplyContractsSamplesDescriptionsWithoutCa.rispostaUe42",
                            "supplyContractsSamplesDescriptionsWithCa.risp6",
                            "supplyContractsSamplesDescriptionsWithCa.rispostaUe43",
                            "sezionesub35.rispostaFornitasub13",
                            "supplyContractsCertificatesQc.risp7",
                            "supplyContractsCertificatesQc.rispostaUe44",
                            "certificateIndependentBodiesAboutQa.risp8",
                            "certificateIndependentBodiesAboutQa.rispostaUe45",
                            "certificateIndependentBodiesAboutEnvironmental.risp9",
                            "certificateIndependentBodiesAboutEnvironmental.rispostaUe46",
                            "sezionesub36.rispostaFornitasub14",
                            "eoParticipatingProcurementProcedure.risp",
                            "lotsEoTendersTo.risp",
                            "eoReductionOfCandidates.risp",                    
                            "eoRegistered.risp",
                            "procurementReserved.risp",
                            "eoReliesCapacities.risp",
                            "subcontractingThirdParties.risp",              
                            "caLots.risp",
                            "risp",
                            "rispostaUe",                                                        
                            "paymentTaxes.exists",
                            "paymentSocialSecurity.exists",
                            "breachingObligationsEnvironmental.exists",
                            "breachingObligationsSocial.exists",
                            "breachingObligationsLabour.exists",
                            "bankruptcy.exists",
                            "insolvency.exists",
                            "arrangementWithCreditors.exists",
                            "analogousSituation.exists",
                            "assetsAdministeredByLiquidator.exists",
                            "businessActivitiesSuspended.exists",
                            "guiltyGrave.exists",
                            "agreementsWithOtherEO.exists",
                            "conflictInterest.exists",
                            "involvementPreparationProcurement.exists",
                            "earlyTermination.exists",
                            "guiltyMisinterpretation.exists",
                            "nationalExclusionGrounds.exists",
                            "enrolmentProfessionalRegister.exists",
                            "enrolmentTradeRegister.exists",
                            "serviceContractsAuthorisation.exists",
                            "serviceContractsMembership.exists",
                            "supplyContractsSamplesDescriptionsWithoutCa.exists",
                            "supplyContractsSamplesDescriptionsWithCa.exists",
                            "supplyContractsCertificatesQc.exists",
                            "certificateIndependentBodiesAboutQa.exists",
                            "certificateIndependentBodiesAboutEnvironmental.exists",
                            "caLots.exists",
                            "subcontractingThirdParties.exists",
                            "eoReliesCapacities.exists",
                            "procurementReserved.exists",
                            "eoRegistered.exists",
                            "eoReductionOfCandidates.exists",
                            "lotsEoTendersTo.exists",
                            "eoParticipatingProcurementProcedure.exists",
                            

    ];
    
   
  public static DATE_CODE=[ 'signatureDate','dateOfBirth',
                            'criminalConvictionsDateOfConviction',
                            'criminalConvictionsStartDate2',
                            'criminalConvictionsEndDate2',
                            'criminalConvictionsStartDate',
                            'criminalConvictionsEndDate',
                            'corruptionDateOfConviction',
                            'corruptionStartDate2',
                            'corruptionEndDate2',
                            'corruptionStartDate',
                            'corruptionEndDate',
                            'fraudDateOfConviction',
                            'fraudStartDate2',
                            'fraudEndDate2',
                            'fraudStartDate',
                            'fraudEndDate',
                            'terroristOffencesDateOfConviction',
                            'terroristOffencesStartDate2',
                            'terroristOffencesEndDate2',
                            'terroristOffencesStartDate',
                            'terroristOffencesEndDate',
                            'moneyLaunderingDateOfConviction',
                            'moneyLaunderingStartDate2',
                            'moneyLaunderingEndDate2',
                            'moneyLaunderingStartDate',
                            'moneyLaunderingEndDate',
                            'childLabourDateOfConviction',
                            'childLabourStartDate2',
                            'childLabourEndDate2',
                            'childLabourStartDate',
                            'childLabourEndDate',
                            'paymentTaxesDateOfConviction',
                            'paymentTaxesstartDate',
                            'paymentTaxesendDate',
                            'paymentSocialSecurityDateOfConviction',
                            'paymentSocialSecuritystartDate',
                            'paymentSocialSecurityendDate',
                            'nationalExclusionGroundsDateConviction',
                            'nationalExclusionGroundsStartDate',
                            'nationalExclusionGroundsendDate',
                            'nationalExclusionGroundsStartDate2',
                            'nationalExclusionGroundsendDate2',
                            'nationalExclusionGroundsDateAscertainment',
                            'generalYearlyTurnoverStartDate',
                            'generalYearlyTurnoverEndDate',
                            'specificAverageTurnoverStartDate',
                            'specificAverageTurnoverEndDate',
                            'specificYearlyTurnoverStartDate',
                            'specificYearlyTurnoverEndDate',
                            'setupEconomicOperatorYear',
                            'financialRatioStartDate',
                            'financialRatioEndDate',
                            'otherEconomicFinancialRequirementsStartDate',
                            'otherEconomicFinancialRequirementsEndDate',
                            'workContractsPerformanceOfWorksStartDate',
                            'workContractsPerformanceOfWorksEndDate',
                            'supplyContractsPerformanceDeliveriesStartDate',
                            'supplyContractsPerformanceDeliveriesEndDate',
                            'serviceContractsPerformanceServicesStartDate',
                            'serviceContractsPerformanceServicesEndDate',
                            'educationalProfessionalQualificationsQualificationIssueDate'
                    ];
    public static PROCEDURE_TYPE={
                                /*"NS":"Non specificato",
                                "PA":"Procedura aperta",
                                "PR":"Procedura ristretta",
                                "PCN":"Procedura competitiva con negoziazione",
                                "DC":"Dialogo competitivo",
                                "PI":"Partenariato per l'innovazione"    */

                                "PRIOR":"Prior information or periodic indicative notice",
                                "OPEN":"Open procedure",
                                "RESTRICTED":"Restricted procedure",
                                "RESTRICTED_ACCELERATED":"Accelerated restricted procedure",
                                "NEGOTIATED":"Negotiated procedure",
                                "OPEN_RECUR":"Open procedure with recurring quantities",
                                "NEGOTIATED_ACCELERATED":"Accelerated negotiated procedure",
                                "AWARD":"Contract awards",
                                "INFO":"General information",
                                "AWARD_DIRECT":"Direct Award",
                                "COMP_NEGOTIATION":"Competitive procedure with negotiation",
                                "COMP_DIALOGUE":"Competitive dialogue",
                                "DESIGN_CONTEST":"Design contest",
                                "CONCESSION":"Concession award procedure",
                                "CONCESSION_WO_PUB":"Concession award without prior concession notice",
                                "INNOVATION":"Innovation partnership",
                                "AMI":"Call for expressions of interest",
                                "NOT_SPECIFIED":"Not specified",
                                "QUAL":"Qualification system",
                                "CONTESTS_RESULT":"Results of design contests",
                                "NEGOTIATED_WO_CALL":"Negotiated without a prior call for competition",
                                "AWARD_WO_PUB":"Contract award without prior publication",
                                "OTHER":"Other",
                                "NOT_APPLICABLE":"Not applicable",                                
                                "LOV":"Negotiated Procedure for low value contracts",
                                "VDL":"Vendor's list"

    };

        public static PROJECT_TYPE_MAP={
            "1":"WORKS",
            "2":"SUPPLIES",
            "3":"SERVICES"
        };

        public static DOCUMENT_TYPE_MAP={
            "2":"Other",
            "3":"TED_CN",
            "4":"NOJCN",
            "5":"ROJCN",
            "7":"LOJCN"
        };

        public static BID_TYPE_MAP={
            "1":"LOT_ONE",
            "2":"LOT_ONE_MORE",
            "3":"LOT_ALL"
        };
      

        public static PROCEDURE_TYPE_MAP={
            "999":"PRIOR",
            "1": "OPEN",
            "2": "RESTRICTED",
            "1000":"RESTRICTED_ACCELERATED",
            "4": "NEGOTIATED",
            "1001":"OPEN_RECUR",
            "1002":"NEGOTIATED_ACCELERATED",
            "1003":"AWARD",
            "1004":"INFO",
            "12":"AWARD_DIRECT",
            "1005":"COMP_NEGOTIATION",
            "8":"COMP_DIALOGUE",
            "1006":"DESIGN_CONTEST",
            "1007":"CONCESSION",
            "1008":"CONCESSION_WO_PUB",
            "34":"INNOVATION",
            "1010":"AMI",
            "1011":"NOT_SPECIFIED",
            "1012":"QUAL",
            "1013":"CONTESTS_RESULT",
            "9": "NEGOTIATED_WO_CALL",
            "1014":"AWARD_WO_PUB",
            "1015":"OTHER",
            "1016":"NOT_APPLICABLE",
            "1017":"NOT_SPECIFIED",
            "7": "LOV",
            "1018": "VDL"
    };


    public static VALUE_MAP={
        "AED": "AED (United Arab Emirates dirham)" ,
        "AFN": "AFN (Afghani)" ,
        "ALL": "ALL (Lek)" ,
        "AMD": "AMD (Armenian Dram)" ,
        "ANG": "ANG (Netherlands Antillian Guilder)" ,
        "AOA": "AOA (Kwanza)" ,
        "ARS": "ARS (Argentine Peso)" ,
        "AUD": "AUD (Australian Dollar)" ,
        "AWG": "AWG (Aruban Guilder)" ,
        "AZN": "AZN (Azerbaijanian Manat)" ,
        "BAM": "BAM (Convertible Marks)" ,
        "BBD": "BBD (Barbados Dollar)" ,
        "BDT": "BDT (Bangladeshi Taka)" ,
        "BGN": "BGN (Bulgarian Lev)" ,
        "BHD": "BHD (Bahraini Dinar)" ,
        "BIF": "BIF (Burundian Franc)" ,
        "BMD": "BMD (Bermudian Dollar (customarily known as Bermuda Dollar))" ,
        "BND": "BND (Brunei Dollar)" ,
        "BOB": "BOB (Boliviano)" ,
        "BOV": "BOV (Bolivian Mvdol (Funds code))" ,
        "BRL": "BRL (Brazilian Real)" ,
        "BSD": "BSD (Bahamian Dollar)" ,
        "BTN": "BTN (Ngultrum)" ,
        "BWP": "BWP (Pula)" ,
        "BYR": "BYR (Belarussian Ruble)" ,
        "BZD": "BZD (Belize Dollar)" ,
        "CAD": "CAD (Canadian Dollar)" ,
        "CDF": "CDF (Franc Congolais)" ,
        "CHE": "CHE (WIR(Euro (complementary currency))" ,
        "CHF": "CHF (Swiss Franc)" ,
        "CHW": "CHW (WIR Franc (complementary currency))" ,
        "CLF": "CLF (Unidades de formento (Funds code))" ,
        "CLP": "CLP (Chilean Peso)" ,
        "CNY": "CNY (Yuan Renminbi)" ,
        "COP": "COP (Colombian Peso)" ,
        "COU": "COU (Unidad de Valor Real)" ,
        "CRC": "CRC (Costa Rican Colon)" ,
        "CUP": "CUP (Cuban Peso)" ,
        "CVE": "CVE (Cape Verde Escudo)" ,
        "CZK": "CZK (Czech Koruna)" ,
        "DJF": "DJF (Djibouti Franc)" ,
        "DKK": "DKK (Danish Krone)" ,
        "DOP": "DOP (Dominican Peso)" ,
        "DZD": "DZD (Algerian Dinar)" ,
        "EEK": "EEK (Kroon)" ,
        "EGP": "EGP (Egyptian Pound)" ,
        "ERN": "ERN (Nakfa)" ,
        "ETB": "ETB (Ethiopian Birr)" ,
        "EUR": "EUR (Euro)" ,
        "FJD": "FJD (Fiji Dollar)" ,
        "FKP": "FKP (Falkland Islands Pound)" ,
        "GBP": "GBP (Pound Sterling)" ,
        "GEL": "GEL (Lari)" ,
        "GHS": "GHS (Cedi)" ,
        "GIP": "GIP (Gibraltar pound)" ,
        "GMD": "GMD (Dalasi)" ,
        "GNF": "GNF (Guinea Franc)" ,
        "GTQ": "GTQ (Quetzal)" ,
        "GYD": "GYD (Guyana Dollar)" ,
        "HKD": "HKD (Hong Kong Dollar)" ,
        "HNL": "HNL (Lempira)" ,
        "HRK": "HRK (Croatian Kuna)" ,
        "HTG": "HTG (Haiti Gourde)" ,
        "HUF": "HUF (Forint)" ,
        "IDR": "IDR (Rupiah)" ,
        "ILS": "ILS (New Israeli Shekel)" ,
        "INR": "INR (Indian Rupee)" ,
        "IQD": "IQD (Iraqi Dinar)" ,
        "IRR": "IRR (Iranian Rial)" ,
        "ISK": "ISK (Iceland Krona)" ,
        "JMD": "JMD (Jamaican Dollar)" ,
        "JOD": "JOD (Jordanian Dinar)" ,
        "JPY": "JPY (Japanese yen)" ,
        "KES": "KES (Kenyan Shilling)" ,
        "KGS": "KGS (Som)" ,
        "KHR": "KHR (Riel)" ,
        "KMF": "KMF (Comoro Franc)" ,
        "KPW": "KPW (North Korean Won)" ,
        "KRW": "KRW (South Korean Won)" ,
        "KWD": "KWD (Kuwaiti Dinar)" ,
        "KYD": "KYD (Cayman Islands Dollar)" ,
        "KZT": "KZT (Tenge)" ,
        "LAK": "LAK (Kip)" ,
        "LBP": "LBP (Lebanese Pound)" ,
        "LKR": "LKR (Sri Lanka Rupee)" ,
        "LRD": "LRD (Liberian Dollar)" ,
        "LSL": "LSL (Loti)" ,
        "LTL": "LTL (Lithuanian Litas)" ,
        "LVL": "LVL (Latvian Lats)" ,
        "LYD": "LYD (Libyan Dinar)" ,
        "MAD": "MAD (Moroccan Dirham)" ,
        "MDL": "MDL (Moldovan Leu)" ,
        "MGA": "MGA (Malagasy Ariary)" ,
        "MKD": "MKD (Denar)" ,
        "MMK": "MMK (Kyat)" ,
        "MNT": "MNT (Tugrik)" ,
        "MOP": "MOP (Pataca)" ,
        "MRO": "MRO (Ouguiya)" ,
        "MTL": "MTL (Maltese Lira)" ,
        "MUR": "MUR (Mauritius Rupee)" ,
        "MVR": "MVR (Rufiyaa)" ,
        "MWK": "MWK (Kwacha)" ,
        "MXN": "MXN (Mexican Peso)" ,
        "MXV": "MXV (Mexican Unidad de Inversion (UDI) (Funds code))" ,
        "MYR": "MYR (Malaysian Ringgit)" ,
        "MZN": "MZN (Metical)" ,
        "NAD": "NAD (Namibian Dollar)" ,
        "NGN": "NGN (Naira)" ,
        "NIO": "NIO (Cordoba Oro)" ,
        "NOK": "NOK (Norwegian Krone)" ,
        "NPR": "NPR (Nepalese Rupee)" ,
        "NZD": "NZD (New Zealand Dollar)" ,
        "OMR": "OMR (Rial Omani)" ,
        "PAB": "PAB (Balboa)" ,
        "PEN": "PEN (Nuevo Sol)" ,
        "PGK": "PGK (Kina)" ,
        "PHP": "PHP (Philippine Peso)" ,
        "PKR": "PKR (Pakistan Rupee)" ,
        "PLN": "PLN (Zloty)" ,
        "PYG": "PYG (Guarani)" ,
        "QAR": "QAR (Qatari Rial)" ,
        "RON": "RON (Romanian New Leu)" ,
        "RSD": "RSD (Serbian Dinar)" ,
        "RUB": "RUB (Russian Ruble)" ,
        "RWF": "RWF (Rwanda Franc)" ,
        "SAR": "SAR (Saudi Riyal)" ,
        "SBD": "SBD (Solomon Islands Dollar)" ,
        "SCR": "SCR (Seychelles Rupee)" ,
        "SDG": "SDG (Sudanese Pound)" ,
        "SSP": "SSP (South Sudanese Pound)" ,
        "SEK": "SEK (Swedish Krona)" ,
        "SGD": "SGD (Singapore Dollar)" ,
        "SHP": "SHP (Saint Helena Pound)" ,
        "SKK": "SKK (Slovak Koruna)" ,
        "SLL": "SLL (Leone)" ,
        "SOS": "SOS (Somali Shilling)" ,
        "SRD": "SRD (Surinam Dollar)" ,
        "STD": "STD (Dobra)" ,
        "SYP": "SYP (Syrian Pound)" ,
        "SZL": "SZL (Lilangeni)" ,
        "THB": "THB (Baht)" ,
        "TJS": "TJS (Somoni)" ,
        "TMM": "TMM (Manat)" ,
        "TND": "TND (Tunisian Dinar)" ,
        "TOP": "TOP (Pa'anga)" ,
        "TRY": "TRY (New Turkish Lira)" ,
        "TTD": "TTD (Trinidad and Tobago Dollar)" ,
        "TWD": "TWD (New Taiwan Dollar)" ,
        "TZS": "TZS (Tanzanian Shilling)" ,
        "UAH": "UAH (Hryvnia)" ,
        "UGX": "UGX (Uganda Shilling)" ,
        "USD": "USD (US Dollar)" ,
        "USN": "USN (USN)" ,
        "USS": "USS (USS)" ,
        "UYU": "UYU (Peso Uruguayo)" ,
        "UZS": "UZS (Uzbekistan Som)" ,
        "VEB": "VEB (Venezuelan bolívar)" ,
        "VND": "VND (Vietnamese đồng)" ,
        "VUV": "VUV (Vatu)" ,
        "WST": "WST (Samoan Tala)" ,
        "XAF": "XAF (CFA(Franc BEAC)" ,
        "XAG": "XAG (Silver (one Troy ounce))" ,
        "XAU": "XAU (Gold (one Troy ounce))" ,
        "XBA": "XBA (European Composite Unit (EURCO) (Bonds market unit))" ,
        "XBB": "XBB (European Monetary Unit (E.M.U.-6) (Bonds market unit))" ,
        "XBC": "XBC (European Unit of Account 9 (E.U.A.-9) (Bonds market unit))" ,
        "XBD": "XBD (European Unit of Account 17 (E.U.A.-17) (Bonds market unit))" ,
        "XCD": "XCD (East Caribbean Dollar)" ,
        "XDR": "XDR (Special Drawing Rights)" ,
        "XFO": "XFO (Gold franc (special settlement currency))" ,
        "XFU": "XFU (UIC franc (special settlement currency))" ,
        "XOF": "XOF (CFA Franc BCEAO)" ,
        "XPD": "XPD (Palladium (one Troy ounce))" ,
        "XPF": "XPF (CFP franc)" ,
        "XPT": "XPT (Platinum (one Troy ounce))" ,
        "XTS": "XTS (Code reserved for testing purposes)" ,
        "XXX": "XXX (No currency)" ,
        "YER": "YER (Yemeni Rial)" ,
        "ZAR": "ZAR (South African Rand)" ,
        "ZMK": "ZMK (Kwacha)" ,
        "ZWD": "ZWD (Zimbabwe Dollar)"};

   
        public static MAPINFO_AUTHTORITY:"authority";
        public static MAPINFO_NAME:"name";         
        public static MAPINFO_COUNTRY:"country";
        public static MAPINFO_PROFILEURI:"profileURI";
        public static MAPINFO_VATNUMBER:"vatNumber";
        public static MAPINFO_WEBSITE:"website";
        public static MAPINFO_EMAIL:"email";
        public static MAPINFO_STREET:"street";
        public static MAPINFO_CITY:"city";
        public static MAPINFO_POSTALCODE:"postalCode";
        public static MAPINFO_ANOTHERNATIONALID:"anotherNationalId";
        public static MAPINFO_CONTACTNAME:"contactName";
        public static MAPINFO_CONTACTPHONE:"contactPhone";
        public static MAPINFO_CONTACTFAX:"contactFax";
        public static MAPINFO_CONTACTEMAIL:"contactEmail";
        public static MAPINFO_LOTS:"lots";
        public static MAPINFO_CPV:"codiceCPV-data";
        public static MAPINFO_TIPOPROCEDURA:"tipoProcedura";

        public static SSO_COOKIE_KEY="dgue-session-token";

}