package it.maggioli.eldasoft.dgue.msdgueserver.core.domain.enums.other;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import it.maggioli.eldasoft.dgue.msdgueserver.core.domain.ubl.CodeList;
import lombok.Getter;

/**
 *
 * @author Fabio Gomiero <fabio.gomiero@akera.it>
 * @version 1.0.0
 * @since Mar 03, 2020
 */
@Getter
public enum Currency implements CodeList {

	ADF("ADF", "Andorran franc"),
	ADP("ADP", "Andorran peseta"),
	AED("AED", "UAE dirham"),
	AFA("AFA", "Afghani"),
	AFN("AFN", "Afghani"),
	ALK("ALK", "Lek"),
	ALL("ALL", "Lek"),
	AMD("AMD", "Dram"),
	ANG("ANG", "Netherlands Antillean guilder"),
	AOA("AOA", "Angolan kwanza"),
	AON("AON", "New Angolan kwanza"),
	AOR("AOR", "Angolan kwanza readjustado"),
	ARA("ARA", "Argentine austral"),
	ARL("ARL", "Argentine peso ley"),
	ARM("ARM", "Argentine peso moneda nacional"),
	ARP("ARP", "Argentine peso argentino"),
	ARS("ARS", "Argentine peso"),
	ATS("ATS", "Austrian schilling"),
	AUD("AUD", "Australian dollar"),
	AWG("AWG", "Aruban guilder"),
	AZM("AZM", "Azerbaijani manat"),
	AZN("AZN", "Azerbaijani manat"),
	BAM("BAM", "Bosnia and Herzegovina convertible mark"),
	BBD("BBD", "Barbados dollar"),
	BDT("BDT", "Taka"),
	BEF("BEF", "Belgian franc"),
	BGJ("BGJ", "Lev A/52"),
	BGK("BGK", "Lev A/62"),
	BGL("BGL", "Lev A/99"),
	BGN("BGN", "Lev"),
	BHD("BHD", "Bahraini dinar"),
	BIF("BIF", "Burundi franc"),
	BMD("BMD", "Bermuda dollar"),
	BND("BND", "Brunei dollar"),
	BOB("BOB", "Boliviano"),
	BOP("BOP", "Bolivian peso"),
	BRB("BRB", "Cruzeiro novo"),
	BRC("BRC", "Cruzado"),
	BRE("BRE", "Cruziero"),
	BRL("BRL", "Real"),
	BRN("BRN", "Cruzado novo"),
	BRR("BRR", "Cruziero real"),
	BRZ("BRZ", "Cruziero"),
	BSD("BSD", "Bahamian dollar"),
	BTN("BTN", "Ngultrum"),
	BWP("BWP", "Pula"),
	BYN("BYN", "Belarusian rouble"),
	BYR("BYR", "Belarusian rouble"),
	BZD("BZD", "Belize dollar"),
	CAD("CAD", "Canadian dollar"),
	CDF("CDF", "Congolese franc"),
	CHF("CHF", "Swiss franc"),
	CLE("CLE", "Chilean escudo"),
	CLP("CLP", "Chilean peso"),
	CNY("CNY", "Renminbi-yuan"),
	COP("COP", "Colombian peso"),
	CRC("CRC", "Costa Rican colon"),
	CSJ("CSJ", "Czechoslovak koruna"),
	CSK("CSK", "Czechoslovak koruna"),
	CUC("CUC", "Convertible peso"),
	CUP("CUP", "Cuban peso"),
	CVE("CVE", "Cape Verde escudo"),
	CYP("CYP", "Cypriot pound"),
	CZK("CZK", "Czech koruna"),
	DDM("DDM", "East-German Mark"),
	DEM("DEM", "German mark"),
	DJF("DJF", "Djibouti franc"),
	DKK("DKK", "Danish krone"),
	DOP("DOP", "Dominican peso"),
	DZD("DZD", "Algerian dinar"),
	ECS("ECS", "Ecuadorian sucre"),
	EEK("EEK", "Estonian kroon"),
	EGP("EGP", "Egyptian pound"),
	ERN("ERN", "Nakfa"),
	ESP("ESP", "Peseta"),
	ETB("ETB", "Birr"),
	EUR("EUR", "Euro"),
	FIM("FIM", "Finnish markka"),
	FJD("FJD", "Fiji dollar"),
	FKP("FKP", "Falkland Islands pound"),
	FRF("FRF", "French franc"),
	GBP("GBP", "Pound sterling"),
	GEL("GEL", "Lari"),
	GHC("GHC", "Cedi"),
	GHS("GHS", "Ghana cedi"),
	GIP("GIP", "Gibraltar pound"),
	GMD("GMD", "Dalasi"),
	GNE("GNE", "Syli"),
	GNF("GNF", "Guinean franc"),
	GQE("GQE", "Ekwele"),
	GRD("GRD", "Drachma"),
	GTQ("GTQ", "Quetzal"),
	GWP("GWP", "Guinea-Bissau peso"),
	GYD("GYD", "Guyana dollar"),
	HKD("HKD", "Hong Kong dollar"),
	HNL("HNL", "Lempira"),
	HRK("HRK", "Kuna"),
	HTG("HTG", "Gourde"),
	HUF("HUF", "Forint"),
	IDR("IDR", "Indonesian rupiah"),
	IEP("IEP", "Irish pound"),
	ILP("ILP", "Israeli lira"),
	ILR("ILR", "Shekel"),
	ILS("ILS", "Shekel"),
	INR("INR", "Indian rupee"),
	IQD("IQD", "Iraqi dinar"),
	IRR("IRR", "Iranian rial"),
	ISJ("ISJ", "Icelandic old króna"),
	ISK("ISK", "Iceland króna"),
	ITL("ITL", "Italian lira"),
	JMD("JMD", "Jamaica dollar"),
	JOD("JOD", "Jordanian dinar"),
	JPY("JPY", "Yen"),
	KES("KES", "Kenyan shilling"),
	KGS("KGS", "Som"),
	KHR("KHR", "Riel"),
	KMF("KMF", "Comorian franc"),
	KPW("KPW", "North Korean won"),
	KRW("KRW", "South Korean won"),
	KWD("KWD", "Kuwaiti dinar"),
	KYD("KYD", "Cayman Islands dollar"),
	KZT("KZT", "Tenge"),
	LAJ("LAJ", "Kip"),
	LAK("LAK", "Kip"),
	LBP("LBP", "Lebanese pound"),
	LKR("LKR", "Sri Lankan rupee"),
	LRD("LRD", "Liberian dollar"),
	LSL("LSL", "Loti"),
	LTL("LTL", "Litas"),
	LUF("LUF", "Luxembourg franc"),
	LVL("LVL", "Lats"),
	LYD("LYD", "Libyan dinar"),
	MAD("MAD", "Moroccan dirham"),
	MCF("MCF", "Monegasque franc"),
	MDL("MDL", "Moldovan leu"),
	MGA("MGA", "Ariary"),
	MGF("MGF", "Malagasy franc"),
	MKD("MKD", "Denar"),
	MKN("MKN", "Denar A/93"),
	MLF("MLF", "Mali franc"),
	MMK("MMK", "Kyat"),
	MNT("MNT", "Tugrik"),
	MOP("MOP", "Pataca"),
	MRO("MRO", "Ouguiya"),
	MTL("MTL", "Maltese lira"),
	MTP("MTP", "Maltese pound"),
	MUR("MUR", "Mauritian rupee"),
	MVQ("MVQ", "Maldive rupee"),
	MVR("MVR", "Rufiyaa"),
	MWK("MWK", "Malawian kwacha"),
	MXN("MXN", "Mexican peso"),
	MXP("MXP", "Mexican peso"),
	MYR("MYR", "Ringgit"),
	MZM("MZM", "Metica"),
	MZN("MZN", "Metical) (_S | Meticais"),
	NAD("NAD", "Namibian dollar"),
	NFD("NFD", "Newfoundland dollar"),
	NGN("NGN", "Naira"),
	NIO("NIO", "Córdoba oro"),
	NLG("NLG", "Netherlands guilder"),
	NOK("NOK", "Norwegian krone"),
	NPR("NPR", "Nepalese rupee"),
	NZD("NZD", "New Zealand dollar"),
	OMR("OMR", "Omani rial"),
	PAB("PAB", "Balboa"),
	PEH("PEH", "Sol"),
	PEI("PEI", "Inti"),
	PEN("PEN", "Nuevo sol"),
	PGK("PGK", "Kina"),
	PHP("PHP", "Philippine peso"),
	PKR("PKR", "Pakistani rupee"),
	PLN("PLN", "Zloty"),
	PLZ("PLZ", "Zloty A/94"),
	PTE("PTE", "Portuguese escudo"),
	PYG("PYG", "Guaraní"),
	QAR("QAR", "Qatari rial"),
	ROL("ROL", "Romanian leu A/05"),
	RON("RON", "Romanian leu"),
	RSD("RSD", "Serbian dinar"),
	RUB("RUB", "Russian rouble"),
	RUR("RUR", "Russian rouble A/97"),
	RWF("RWF", "Rwandese franc"),
	SAR("SAR", "Saudi riyal"),
	SBD("SBD", "Solomon Islands dollar"),
	SCR("SCR", "Seychelles rupee"),
	SDD("SDD", "Sudanese dinar"),
	SDG("SDG", "Sudanese pound"),
	SEK("SEK", "Swedish krona"),
	SGD("SGD", "Singapore dollar"),
	SHP("SHP", "Saint Helena pound"),
	SIT("SIT", "Slovenian tolar"),
	SKK("SKK", "Slovak koruna"),
	SLL("SLL", "Leone"),
	SML("SML", "San Marinese lira"),
	SOS("SOS", "Somali shilling"),
	SQS("SQS", "Somaliland shilling"),
	SRD("SRD", "Surinamese dollar"),
	SRG("SRG", "Suriname guilder"),
	SSP("SSP", "South Sudanese pound"),
	STD("STD", "Dobra"),
	SUR("SUR", "Soviet Union rouble"),
	SVC("SVC", "Salvadorian colón"),
	SYP("SYP", "Syrian pound"),
	SZL("SZL", "Lilangeni"),
	THB("THB", "Baht"),
	TJR("TJR", "Tajikistani rouble"),
	TJS("TJS", "Somoni"),
	TMM("TMM", "Turkmen manat"),
	TMT("TMT", "Turkmen manat"),
	TND("TND", "Tunisian dinar"),
	TOP("TOP", "Pa’anga"),
	TPE("TPE", "Portuguese Timorese escudo"),
	TRL("TRL", "Turkish lira A/05"),
	TRY("TRY", "Turkish lira"),
	TTD("TTD", "Trinidad and Tobago dollar"),
	TVD("TVD", "Tuvaluan dollar"),
	TWD("TWD", "New Taiwan dollar"),
	TZS("TZS", "Tanzanian shilling"),
	UAH("UAH", "Hryvnia"),
	UAK("UAK", "Karbovanets"),
	UGS("UGS", "Uganda shilling A/87"),
	UGX("UGX", "Uganda shilling"),
	USD("USD", "US dollar"),
	USN("USN", "US dollar"),
	USS("USS", "US dollar"),
	UYN("UYN", "Uruguay old peso"),
	UYU("UYU", "Uruguayan peso"),
	UZS("UZS", "Sum"),
	VAL("VAL", "Vatican lira"),
	VEB("VEB", "Bolívar fuerte"),
	VEF("VEF", "Bolívar"),
	VNC("VNC", "Old dong"),
	VND("VND", "Dong"),
	VUV("VUV", "Vatu"),
	WST("WST", "Tala"),
	XAF("XAF", "CFA franc (BEAC)}"),
	XCD("XCD", "East Caribbean dollar"),
	XEU("XEU", "European Currency Unit"),
	XOF("XOF", "{CFA Franc (BCEAO)}"),
	XPF("XPF", "CFP franc"),
	XXX("XXX", "No currency"),
	YDD("YDD", "South Yemeni dinar"),
	YER("YER", "Yemeni rial"),
	YUD("YUD", "Yugoslav dinar"),
	YUF("YUF", "Yugoslav dinar"),
	YUG("YUG", "Yugoslav dinar"),
	YUM("YUM", "Yugoslav dinar"),
	YUN("YUN", "Yugoslav dinar"),
	YUO("YUO", "Yugoslav dinar"),
	YUR("YUR", "Yugoslav dinar"),
	YUS("YUS", "Yugoslav dinar"),
	ZAR("ZAR", "Rand"),
	ZMK("ZMK", "Zambian kwacha"),
	ZMW("ZMW", "Zambian kwacha"),
	ZRN("ZRN", "Zaïrean zaïre"),
	ZRZ("ZRZ", "Zaïrean new zaïre"),
	ZWC("ZWC", "Rhodesian dollar"),
	ZWD("ZWD", "Zimbabwe dollar A/06"),
	ZWL("ZWL", "Zimbabwe dollar"),
	ZWN("ZWN", "Zimbabwe dollar A/08"),
	ZWR("ZWR", "Zimbabwe dollar A/09");;

	public static final List<Currency> VALUES = Collections.unmodifiableList(Arrays.asList(values()));//NOSONAR

	private final String code;
	private final String description;

	Currency(String code, String description) {
		this.description = description;
		this.code = code;
	}


	@Override
	public String getListVersionId() {
		return "1.0";
	}

	@Override
	public String getListId() {
		return "CurrencyCode";
	}

	@Override
	public String getListAgencyName() {
		return Agency.EU_COM_OP.getIdentifier();
	}
}
