import { Injectable, Injector } from '@angular/core';
import { IDictionary, SdkBaseService, SdkProvider } from '@maggioli/sdk-commons';
import { SdkComboBoxItem } from '@maggioli/sdk-controls';
import { TranslateService } from '@ngx-translate/core';
import { get, isEmpty } from 'lodash-es';
import { Observable, Observer } from 'rxjs';

import { StoreService } from '../services/storeService';
import { AppCostants } from '../utils/dgue-constants';

@Injectable()
export class TabellatiComboProvider extends SdkBaseService implements SdkProvider {

    constructor(inj: Injector, public store: StoreService,) {
        super(inj);
    }

    public run(providerArgs: IDictionary<any>): Function {
        return (args: IDictionary<any>): Observable<Array<SdkComboBoxItem>> => {
            let listCode: string = get(args, 'listCode');
            if (!isEmpty(listCode)) {                
                let listaTabellato: Array<SdkComboBoxItem>;
                if (this.store.viewElement(AppCostants.STORE_LANG) == 'it') {
                    listaTabellato = this.getTabellatiMap()[listCode];
                } else {
                    listaTabellato = this.getTabellatiMapEn()[listCode];
                }
                if (isEmpty(listaTabellato)) {
                    listaTabellato = new Array<SdkComboBoxItem>();
                }
                return new Observable((ob: Observer<Array<SdkComboBoxItem>>) => {
                    ob.next(listaTabellato);
                    ob.complete();
                });
            }
        }
    }

    // #region Getters

    private get translateService(): TranslateService { return this.injectable(TranslateService) }

    // #endregion

    public getTabellatoDescription(tabellatoCode: string, tabellatoKey: string) {
        let righeTabellato;
        if (this.store.viewElement(AppCostants.STORE_LANG) == 'it') {
            righeTabellato = this.getTabellatiMap()[tabellatoCode];
        } else {
            righeTabellato = this.getTabellatiMapEn()[tabellatoCode];
        }

        let result = ""
        if (!isEmpty(righeTabellato)) {
            righeTabellato.forEach(riga => {
                if (riga.key === tabellatoKey) {
                    result = riga.value;
                } else if (riga.value === tabellatoKey) {
                    result = riga.value;
                }
            });
        }
        return result;
    }

    public getTabellatoKey(tabellatoCode: string, tabellatoDescription: string) {
        let righeTabellato;
        if (this.store.viewElement(AppCostants.STORE_LANG) == 'it') {
            righeTabellato = this.getTabellatiMap()[tabellatoCode];
        } else {
            righeTabellato = this.getTabellatiMapEn()[tabellatoCode];
        }

        let result = ""
        if (!isEmpty(righeTabellato)) {
            righeTabellato.forEach(riga => {
                if (riga.key === tabellatoDescription) {
                    result = riga.key;
                } else if (riga.value === tabellatoDescription) {
                    result = riga.key;
                }
            });
        }
        return result;
    }

    public getTabellatiMap(): IDictionary<any> {
        return {
            'paesi': [
                { key: "AD", value: "Andorra" },
                { key: "AE", value: "United Arab Emirates" },
                { key: "AF", value: "Afghanistan" },
                { key: "AG", value: "Antigua and Barbuda" },
                { key: "AI", value: "Anguilla" },
                { key: "AL", value: "Albania" },
                { key: "AM", value: "Armenia" },
                { key: "AO", value: "Angola" },
                { key: "AQ", value: "Antarctica" },
                { key: "AR", value: "Argentina" },
                { key: "AS", value: "American Samoa" },
                { key: "AT", value: "Austria" },
                { key: "AU", value: "Australia" },
                { key: "AW", value: "Aruba" },
                { key: "AX", value: "Åland Islands" },
                { key: "AZ", value: "Azerbaijan" },
                { key: "BA", value: "Bosnia and Herzegovina" },
                { key: "BB", value: "Barbados" },
                { key: "BD", value: "Bangladesh" },
                { key: "BE", value: "Belgium" },
                { key: "BF", value: "Burkina Faso" },
                { key: "BG", value: "Bulgaria" },
                { key: "BH", value: "Bahrain" },
                { key: "BI", value: "Burundi" },
                { key: "BJ", value: "Benin" },
                { key: "BL", value: "Saint Barthélemy" },
                { key: "BM", value: "Bermuda" },
                { key: "BN", value: "Brunei Darussalam" },
                { key: "BO", value: "Bolivia, Plurinational State of" },
                { key: "BQ", value: "Bonaire, Sint Eustatius and Saba" },
                { key: "BR", value: "Brazil" },
                { key: "BS", value: "Bahamas" },
                { key: "BT", value: "Bhutan" },
                { key: "BV", value: "Bouvet Island" },
                { key: "BW", value: "Botswana" },
                { key: "BY", value: "Belarus" },
                { key: "BZ", value: "Belize" },
                { key: "CA", value: "Canada" },
                { key: "CC", value: "Cocos (Keeling) Islands" },
                { key: "CD", value: "Congo, the Democratic Republic of the" },
                { key: "CF", value: "Central African Republic" },
                { key: "CG", value: "Congo" },
                { key: "CH", value: "Switzerland" },
                { key: "CI", value: "Côte d'Ivoire" },
                { key: "CK", value: "Cook Islands" },
                { key: "CL", value: "Chile" },
                { key: "CM", value: "Cameroon" },
                { key: "CN", value: "China" },
                { key: "CO", value: "Colombia" },
                { key: "CR", value: "Costa Rica" },
                { key: "CU", value: "Cuba" },
                { key: "CV", value: "Cabo Verde" },
                { key: "CW", value: "Curaçao" },
                { key: "CX", value: "Christmas Island" },
                { key: "CY", value: "Cyprus" },
                { key: "CZ", value: "Czech Republic" },
                { key: "DE", value: "Germany" },
                { key: "DJ", value: "Djibouti" },
                { key: "DK", value: "Denmark" },
                { key: "DM", value: "Dominica" },
                { key: "DO", value: "Dominican Republic" },
                { key: "DZ", value: "Algeria" },
                { key: "EC", value: "Ecuador" },
                { key: "EE", value: "Estonia" },
                { key: "EG", value: "Egypt" },
                { key: "EH", value: "Western Sahara" },
                { key: "ER", value: "Eritrea" },
                { key: "ES", value: "Spain" },
                { key: "ET", value: "Ethiopia" },
                { key: "FI", value: "Finland" },
                { key: "FJ", value: "Fiji" },
                { key: "FK", value: "Falkland Islands (Malvinas)" },
                { key: "FM", value: "Micronesia, Federated States of" },
                { key: "FO", value: "Faroe Islands" },
                { key: "FR", value: "France" },
                { key: "GA", value: "Gabon" },
                { key: "GB", value: "United Kingdom of Great Britain and Northern Ireland" },
                { key: "GD", value: "Grenada" },
                { key: "GE", value: "Georgia" },
                { key: "GF", value: "French Guiana" },
                { key: "GG", value: "Guernsey" },
                { key: "GH", value: "Ghana" },
                { key: "GI", value: "Gibraltar" },
                { key: "GL", value: "Greenland" },
                { key: "GM", value: "Gambia" },
                { key: "GN", value: "Guinea" },
                { key: "GP", value: "Guadeloupe" },
                { key: "GQ", value: "Equatorial Guinea" },
                { key: "GR", value: "Greece" },
                { key: "GS", value: "South Georgia and the South Sandwich Islands" },
                { key: "GT", value: "Guatemala" },
                { key: "GU", value: "Guam" },
                { key: "GW", value: "Guinea-Bissau" },
                { key: "GY", value: "Guyana" },
                { key: "HK", value: "Hong Kong" },
                { key: "HM", value: "Heard Island and McDonald Islands" },
                { key: "HN", value: "Honduras" },
                { key: "HR", value: "Croatia" },
                { key: "HT", value: "Haiti" },
                { key: "HU", value: "Hungary" },
                { key: "ID", value: "Indonesia" },
                { key: "IE", value: "Ireland" },
                { key: "IL", value: "Israel" },
                { key: "IM", value: "Isle of Man" },
                { key: "IN", value: "India" },
                { key: "IO", value: "British Indian Ocean Territory" },
                { key: "IQ", value: "Iraq" },
                { key: "IR", value: "Iran, Islamic Republic of" },
                { key: "IS", value: "Iceland" },
                { key: "IT", value: "Italy" },
                { key: "JE", value: "Jersey" },
                { key: "JM", value: "Jamaica" },
                { key: "JO", value: "Jordan" },
                { key: "JP", value: "Japan" },
                { key: "KE", value: "Kenya" },
                { key: "KG", value: "Kyrgyzstan" },
                { key: "KH", value: "Cambodia" },
                { key: "KI", value: "Kiribati" },
                { key: "KM", value: "Comoros" },
                { key: "KN", value: "Saint Kitts and Nevis" },
                { key: "KP", value: "Korea, Democratic People's Republic of" },
                { key: "KR", value: "Korea, Republic of" },
                { key: "KW", value: "Kuwait" },
                { key: "KY", value: "Cayman Islands" },
                { key: "KZ", value: "Kazakhstan" },
                { key: "LA", value: "Lao People's Democratic Republic" },
                { key: "LB", value: "Lebanon" },
                { key: "LC", value: "Saint Lucia" },
                { key: "LI", value: "Liechtenstein" },
                { key: "LK", value: "Sri Lanka" },
                { key: "LR", value: "Liberia" },
                { key: "LS", value: "Lesotho" },
                { key: "LT", value: "Lithuania" },
                { key: "LU", value: "Luxembourg" },
                { key: "LV", value: "Latvia" },
                { key: "LY", value: "Libya" },
                { key: "MA", value: "Morocco" },
                { key: "MC", value: "Monaco" },
                { key: "MD", value: "Moldova, Republic of" },
                { key: "ME", value: "Montenegro" },
                { key: "MF", value: "Saint Martin (French part)" },
                { key: "MG", value: "Madagascar" },
                { key: "MH", value: "Marshall Islands" },
                { key: "MK", value: "Macedonia, the former Yugoslav Republic of" },
                { key: "ML", value: "Mali" },
                { key: "MM", value: "Myanmar" },
                { key: "MN", value: "Mongolia" },
                { key: "MO", value: "Macao" },
                { key: "MP", value: "Northern Mariana Islands" },
                { key: "MQ", value: "Martinique" },
                { key: "MR", value: "Mauritania" },
                { key: "MS", value: "Montserrat" },
                { key: "MT", value: "Malta" },
                { key: "MU", value: "Mauritius" },
                { key: "MV", value: "Maldives" },
                { key: "MW", value: "Malawi" },
                { key: "MX", value: "Mexico" },
                { key: "MY", value: "Malaysia" },
                { key: "MZ", value: "Mozambique" },
                { key: "NA", value: "Namibia" },
                { key: "NC", value: "New Caledonia" },
                { key: "NE", value: "Niger" },
                { key: "NF", value: "Norfolk Island" },
                { key: "NG", value: "Nigeria" },
                { key: "NI", value: "Nicaragua" },
                { key: "NL", value: "Netherlands" },
                { key: "NO", value: "Norway" },
                { key: "NP", value: "Nepal" },
                { key: "NR", value: "Nauru" },
                { key: "NU", value: "Niue" },
                { key: "NZ", value: "New Zealand" },
                { key: "OM", value: "Oman" },
                { key: "PA", value: "Panama" },
                { key: "PE", value: "Peru" },
                { key: "PF", value: "French Polynesia" },
                { key: "PG", value: "Papua New Guinea" },
                { key: "PH", value: "Philippines" },
                { key: "PK", value: "Pakistan" },
                { key: "PL", value: "Poland" },
                { key: "PM", value: "Saint Pierre and Miquelon" },
                { key: "PN", value: "Pitcairn" },
                { key: "PR", value: "Puerto Rico" },
                { key: "PS", value: "Palestine, State of" },
                { key: "PT", value: "Portugal" },
                { key: "PW", value: "Palau" },
                { key: "PY", value: "Paraguay" },
                { key: "QA", value: "Qatar" },
                { key: "RE", value: "Réunion" },
                { key: "RO", value: "Romania" },
                { key: "RS", value: "Serbia" },
                { key: "RU", value: "Russian Federation" },
                { key: "RW", value: "Rwanda" },
                { key: "SA", value: "Saudi Arabia" },
                { key: "SB", value: "Solomon Islands" },
                { key: "SC", value: "Seychelles" },
                { key: "SD", value: "Sudan" },
                { key: "SE", value: "Sweden" },
                { key: "SG", value: "Singapore" },
                { key: "SH", value: "Saint Helena, Ascension and Tristan da Cunha" },
                { key: "SI", value: "Slovenia" },
                { key: "SJ", value: "Svalbard and Jan Mayen" },
                { key: "SK", value: "Slovakia" },
                { key: "SL", value: "Sierra Leone" },
                { key: "SM", value: "San Marino" },
                { key: "SN", value: "Senegal" },
                { key: "SO", value: "Somalia" },
                { key: "SR", value: "Suriname" },
                { key: "SS", value: "South Sudan" },
                { key: "ST", value: "Sao Tome and Principe" },
                { key: "SV", value: "El Salvador" },
                { key: "SX", value: "Sint Maarten (Dutch part)" },
                { key: "SY", value: "Syrian Arab Republic" },
                { key: "SZ", value: "Swaziland" },
                { key: "TC", value: "Turks and Caicos Islands" },
                { key: "TD", value: "Chad" },
                { key: "TF", value: "French Southern Territories" },
                { key: "TG", value: "Togo" },
                { key: "TH", value: "Thailand" },
                { key: "TJ", value: "Tajikistan" },
                { key: "TK", value: "Tokelau" },
                { key: "TL", value: "Timor-Leste" },
                { key: "TM", value: "Turkmenistan" },
                { key: "TN", value: "Tunisia" },
                { key: "TO", value: "Tonga" },
                { key: "TR", value: "Turkey" },
                { key: "TT", value: "Trinidad and Tobago" },
                { key: "TV", value: "Tuvalu" },
                { key: "TW", value: "Taiwan, Province of China" },
                { key: "TZ", value: "Tanzania, United Republic of" },
                { key: "UA", value: "Ukraine" },
                { key: "UG", value: "Uganda" },
                { key: "UM", value: "United States Minor Outlying Islands" },
                { key: "US", value: "United States of America" },
                { key: "UY", value: "Uruguay" },
                { key: "UZ", value: "Uzbekistan" },
                { key: "VA", value: "Holy See" },
                { key: "VC", value: "Saint Vincent and the Grenadines" },
                { key: "VE", value: "Venezuela, Bolivarian Republic of" },
                { key: "VG", value: "Virgin Islands, British" },
                { key: "VI", value: "Virgin Islands, U.S." },
                { key: "VN", value: "Viet Nam" },
                { key: "VU", value: "Vanuatu" },
                { key: "WF", value: "Wallis and Futuna" },
                { key: "WS", value: "Samoa" },
                { key: "XK", value: "Kosovo" },
                { key: "YE", value: "Yemen" },
                { key: "YT", value: "Mayotte" },
                { key: "ZA", value: "South Africa" },
                { key: "ZM", value: "Zambia" },
                { key: "ZW", value: "Zimbabwe" }

            ],
            "sino": [
                { key: "true", value: this.translateService.instant('COMBOBOX.SI') },
                { key: "false", value: this.translateService.instant('COMBOBOX.NO') }
            ],
            "IndustryClassificationCode": [
                { key: "MICRO", value: "Micro impresa" },
                { key: "SMALL", value: "Piccola impresa" },
                { key: "MEDIUM", value: "Media impresa" },
                { key: "SME", value: "Piccole o Medie Imprese" },
                { key: "LARGE", value: "Non PMI, Grande Azienda" }
            ],
            "financialRatioType": [
                { key: "R11", value: "Assets to Equity ratio" },
                { key: "R12", value: "Liabilities to Equity ratio " },
                { key: "R13", value: "Current assets/Total assets " },
                { key: "R14", value: "Other financial assets and cash and bank/ Total assets" },
                { key: "R15", value: "Non-current debt/ Total assets " },
                { key: "R16", value: "Current debt/Total assets " },
                { key: "R21", value: "Financial income net of charges other than interest/EBITDA" },
                { key: "R22", value: "EBITDA/Interest on financial debt" },
                { key: "R23", value: "Interest burden" },
                { key: "R24", value: "Interest and similar charges/Net turnove" },
                { key: "R25", value: "Interest and similar charges/Gross operating profit" },
                { key: "R26", value: "Net financial income/Gross operating profit" },
                { key: "R27", value: "Gross operating profit/Total net debt" },
                { key: "R31", value: "Gross value added/Net turnove" },
                { key: "R32", value: "Gross operating profit/Net turnover (ROS)" },
                { key: "R33", value: "EBITDA/Net turnove" },
                { key: "R34", value: "Net operating profit/Net turnover" },
                { key: "R35", value: "EBIT/Net turnover" },
                { key: "R36", value: "EBT/Net turnover" },
                { key: "R37", value: "Net financial income/Net turnover" },
                { key: "R38", value: "Return on equity" },
                { key: "R39", value: "Net operating profit/Total assets" },
                { key: "R310", value: "Profit or loss for the year before taxes/Equity" },
                { key: "R41", value: "Asset turnover ratio" },
                { key: "R42", value: "Employee expenses/Gross value added" },
                { key: "R51", value: "Inventories/Net turnover" },
                { key: "R52", value: "Trade receivables/Net turnover" },
                { key: "R53", value: "Trade payables/Net turnover" },
                { key: "R54", value: "Operating working capital/Net turnover" }
            ],
            "tipoProcedura": [
                { key: "PRIOR", value: "Informazioni preliminari o avviso periodico indicativo" },
                { key: "OPEN", value: "Procedura aperta" },
                { key: "RESTRICTED", value: "Procedura ristretta" },
                { key: "RESTRICTED_ACCELERATED", value: "Procedura Ristretta Accelerata" },
                { key: "NEGOTIATED", value: "Procedura negoziata senza previa pubblicazione del bando" },
                { key: "OPEN_RECUR", value: "Procedura aperta con quantità ricorrenti" },
                { key: "NEGOTIATED_ACCELERATED", value: "Procedura Negoziata Accelerata" },
                { key: "AWARD", value: "Aggiudicazioni" },
                { key: "INFO", value: "Informazione generale" },
                { key: "AWARD_DIRECT", value: "Affidamento diretto ex art. 5 della legge n.381/91" },
                { key: "COMP_NEGOTIATION", value: "Procedura competitiva con negoziazione" },
                { key: "COMP_DIALOGUE", value: "Dialogo competitivo" },
                { key: "DESIGN_CONTEST", value: "Concorso di progettazione" },
                { key: "CONCESSION", value: "Procedura di aggiudicazione delle concessione" },
                { key: "CONCESSION_WO_PUB", value: "Aggiudicazione di una concessione senza previa pubblicazione di un bando di concessione" },
                { key: "INNOVATION", value: "Partenariato per l'innovazione" },
                { key: "AMI", value: "Invito a manifestazioni di interesse" },
                { key: "NOT_SPECIFIED", value: "Non specificato" },
                { key: "QUAL", value: "Sistema di qualificazione" },
                { key: "CONTESTS_RESULT", value: "Risultati dei concorsi di progettazione" },
                { key: "NEGOTIATED_WO_CALL", value: "Procedura negoziata previa pubblicazione del bando" },
                { key: "AWARD_WO_PUB", value: "Aggiudicazione dell'appalto senza pubblicazione preliminare" },
                { key: "OTHER", value: "Altro" },
                { key: "NOT_APPLICABLE", value: "Non applicabile" },
                { key: "LOV", value: "Affidamento in economia - cottimo fiduciario" },
                { key: "VDL", value: "Lista di fornitori" }













            ],
            "ruoloOperatoreEconomico": [
                /*DEPRECATO{ key: "SCLE", value: "Aggiudicatario Singolo/ Capogruppo" },*/
                { key: "GM", value: "Componente" },
                { key: "OERON", value: "Ausiliario" },
                { key: "OENRON", value: "Subappaltatore" },
                { key: "SC", value: "Aggiudicatario Singolo" },
                { key: "LE", value: "Capogruppo" }
            ],
            "bidType": [
                { key: "LOT_ALL", value: "Presentazione di un'offerta per tutti i lotti" },
                { key: "LOT_ONE", value: "Presentazione di un'offerta per un solo lotto" },
                { key: "LOT_ONE_MORE", value: "Presentazione di un'offerta per uno o più lotti" },
                { key: "OTHER", value: "Altro" },
                { key: "NOT_APPLICABLE", value: "Non applicabile" },
                { key: "NOT_SPECIFIED", value: "Non specificato" }
            ],
            "DocRefContentType": [
                { key: "TED_CN", value: "Avviso di Appalto Pubblico pubblicato sul TED (Gazzetta Ufficiale dell'Ufficio Pubblicazioni dell'UE)" },
                { key: "ESPD_REQUEST", value: "Richiesta di Documento di Gara Unico Europeo emessa da una Stazione Appaltante" },
                { key: "TECC016", value: "Lettera di intenti" },
                { key: "TECC017", value: "Status della Persona Giuridica" },
                { key: "Other", value: "Altro tipo di riferimento ad un documento" },
                { key: "TECC018", value: "Avviso di nomina delle persone autorizzate a rappresentare l'offerente" },
                { key: "TECC019", value: "Documento di registrazione IVA" },
                { key: "TECC020", value: "Documento di identità" },
                { key: "TECC021", value: "Motivi di esenzione dall'IVA" },
                { key: "TECC022", value: "Giustificazione per il subappalto" },
                { key: "TECC024", value: "Potere di rappresentanza" },
                { key: "NOJCN", value: "Avviso di Appalto Pubblico (CN) pubblicato su una Gazzetta Ufficiale Nazionale" },
                { key: "ROJCN", value: "Avviso di Appalto Pubblico (CN) pubblicato su una Gazzetta Ufficiale Regionale" },
                { key: "LOJCN", value: "Avviso di Appalto Pubblico (CN) Pubblicato su un Bollettino Locale" },
                { key: "NOJPIN", value: "Avviso di preinformazione (PIN) pubblicato su una Gazzetta Ufficiale Nazionale" },
                { key: "ROJPIN", value: "Avviso di preinformazione (PIN) pubblicato su una Gazzetta Ufficiale Regionale" },
                { key: "LOJPIN", value: "Avviso di preinformazione (PIN) Pubblicato su un Bollettino Locale" },
                { key: "NOJCAN", value: "Avviso di aggiudicazione (CAN) pubblicato su una Gazzetta Ufficiale Nazionale" },
                { key: "ROJCAN", value: "Avviso di aggiudicazione (CAN) pubblicato su una Gazzetta Ufficiale Regionale" },
                { key: "LOJCAN", value: "Avviso di aggiudicazione (CAN) Pubblicato su un Bollettino Locale" }
            ],
            "projectType": [
                { key: "WORKS", value: "Lavori" },
                { key: "SUPPLIES", value: "Forniture" },
                { key: "COMBINED", value: "Appalti misti" },
                { key: "SERVICES", value: "Servizi" },
                { key: "OTHER", value: "Altro" },
                { key: "NOT_APPLICABLE", value: "Non applicabile" },
                { key: "NOT_SPECIFIED", value: "Non specificato" },
                { key: "CON_PUBLIC_WORKS", value: "Concessione di lavori pubblici" },
                { key: "CON_SERVICE", value: "Concessione di servizi" },
            ],
            "typeOfRequirements": [
                { key: "RADIO_BUTTON_TRUE", value: "Requisiti economico finanziari" },
                { key: "RADIO_BUTTON_FALSE", value: "Requisiti di valutazione" },
            ],
            "tipoMoneta": [
                { key: "AED", value: "AED (United Arab Emirates dirham)" },
                { key: "AFN", value: "AFN (Afghani)" },
                { key: "ALL", value: "ALL (Lek)" },
                { key: "AMD", value: "AMD (Armenian Dram)" },
                { key: "ANG", value: "ANG (Netherlands Antillian Guilder)" },
                { key: "AOA", value: "AOA (Kwanza)" },
                { key: "ARS", value: "ARS (Argentine Peso)" },
                { key: "AUD", value: "AUD (Australian Dollar)" },
                { key: "AWG", value: "AWG (Aruban Guilder)" },
                { key: "AZN", value: "AZN (Azerbaijanian Manat)" },
                { key: "BAM", value: "BAM (Convertible Marks)" },
                { key: "BBD", value: "BBD (Barbados Dollar)" },
                { key: "BDT", value: "BDT (Bangladeshi Taka)" },
                { key: "BGN", value: "BGN (Bulgarian Lev)" },
                { key: "BHD", value: "BHD (Bahraini Dinar)" },
                { key: "BIF", value: "BIF (Burundian Franc)" },
                { key: "BMD", value: "BMD (Bermudian Dollar (customarily known as Bermuda Dollar))" },
                { key: "BND", value: "BND (Brunei Dollar)" },
                { key: "BOB", value: "BOB (Boliviano)" },
                { key: "BOV", value: "BOV (Bolivian Mvdol (Funds code))" },
                { key: "BRL", value: "BRL (Brazilian Real)" },
                { key: "BSD", value: "BSD (Bahamian Dollar)" },
                { key: "BTN", value: "BTN (Ngultrum)" },
                { key: "BWP", value: "BWP (Pula)" },
                { key: "BYR", value: "BYR (Belarussian Ruble)" },
                { key: "BZD", value: "BZD (Belize Dollar)" },
                { key: "CAD", value: "CAD (Canadian Dollar)" },
                { key: "CDF", value: "CDF (Franc Congolais)" },
                { key: "CHE", value: "CHE (WIR(Euro (complementary currency))" },
                { key: "CHF", value: "CHF (Swiss Franc)" },
                { key: "CHW", value: "CHW (WIR Franc (complementary currency))" },
                { key: "CLF", value: "CLF (Unidades de formento (Funds code))" },
                { key: "CLP", value: "CLP (Chilean Peso)" },
                { key: "CNY", value: "CNY (Yuan Renminbi)" },
                { key: "COP", value: "COP (Colombian Peso)" },
                { key: "COU", value: "COU (Unidad de Valor Real)" },
                { key: "CRC", value: "CRC (Costa Rican Colon)" },
                { key: "CUP", value: "CUP (Cuban Peso)" },
                { key: "CVE", value: "CVE (Cape Verde Escudo)" },
                { key: "CZK", value: "CZK (Czech Koruna)" },
                { key: "DJF", value: "DJF (Djibouti Franc)" },
                { key: "DKK", value: "DKK (Danish Krone)" },
                { key: "DOP", value: "DOP (Dominican Peso)" },
                { key: "DZD", value: "DZD (Algerian Dinar)" },
                { key: "EEK", value: "EEK (Kroon)" },
                { key: "EGP", value: "EGP (Egyptian Pound)" },
                { key: "ERN", value: "ERN (Nakfa)" },
                { key: "ETB", value: "ETB (Ethiopian Birr)" },
                { key: "EUR", value: "EUR (Euro)" },
                { key: "FJD", value: "FJD (Fiji Dollar)" },
                { key: "FKP", value: "FKP (Falkland Islands Pound)" },
                { key: "GBP", value: "GBP (Pound Sterling)" },
                { key: "GEL", value: "GEL (Lari)" },
                { key: "GHS", value: "GHS (Cedi)" },
                { key: "GIP", value: "GIP (Gibraltar pound)" },
                { key: "GMD", value: "GMD (Dalasi)" },
                { key: "GNF", value: "GNF (Guinea Franc)" },
                { key: "GTQ", value: "GTQ (Quetzal)" },
                { key: "GYD", value: "GYD (Guyana Dollar)" },
                { key: "HKD", value: "HKD (Hong Kong Dollar)" },
                { key: "HNL", value: "HNL (Lempira)" },
                { key: "HRK", value: "HRK (Croatian Kuna)" },
                { key: "HTG", value: "HTG (Haiti Gourde)" },
                { key: "HUF", value: "HUF (Forint)" },
                { key: "IDR", value: "IDR (Rupiah)" },
                { key: "ILS", value: "ILS (New Israeli Shekel)" },
                { key: "INR", value: "INR (Indian Rupee)" },
                { key: "IQD", value: "IQD (Iraqi Dinar)" },
                { key: "IRR", value: "IRR (Iranian Rial)" },
                { key: "ISK", value: "ISK (Iceland Krona)" },
                { key: "JMD", value: "JMD (Jamaican Dollar)" },
                { key: "JOD", value: "JOD (Jordanian Dinar)" },
                { key: "JPY", value: "JPY (Japanese yen)" },
                { key: "KES", value: "KES (Kenyan Shilling)" },
                { key: "KGS", value: "KGS (Som)" },
                { key: "KHR", value: "KHR (Riel)" },
                { key: "KMF", value: "KMF (Comoro Franc)" },
                { key: "KPW", value: "KPW (North Korean Won)" },
                { key: "KRW", value: "KRW (South Korean Won)" },
                { key: "KWD", value: "KWD (Kuwaiti Dinar)" },
                { key: "KYD", value: "KYD (Cayman Islands Dollar)" },
                { key: "KZT", value: "KZT (Tenge)" },
                { key: "LAK", value: "LAK (Kip)" },
                { key: "LBP", value: "LBP (Lebanese Pound)" },
                { key: "LKR", value: "LKR (Sri Lanka Rupee)" },
                { key: "LRD", value: "LRD (Liberian Dollar)" },
                { key: "LSL", value: "LSL (Loti)" },
                { key: "LTL", value: "LTL (Lithuanian Litas)" },
                { key: "LVL", value: "LVL (Latvian Lats)" },
                { key: "LYD", value: "LYD (Libyan Dinar)" },
                { key: "MAD", value: "MAD (Moroccan Dirham)" },
                { key: "MDL", value: "MDL (Moldovan Leu)" },
                { key: "MGA", value: "MGA (Malagasy Ariary)" },
                { key: "MKD", value: "MKD (Denar)" },
                { key: "MMK", value: "MMK (Kyat)" },
                { key: "MNT", value: "MNT (Tugrik)" },
                { key: "MOP", value: "MOP (Pataca)" },
                { key: "MRO", value: "MRO (Ouguiya)" },
                { key: "MTL", value: "MTL (Maltese Lira)" },
                { key: "MUR", value: "MUR (Mauritius Rupee)" },
                { key: "MVR", value: "MVR (Rufiyaa)" },
                { key: "MWK", value: "MWK (Kwacha)" },
                { key: "MXN", value: "MXN (Mexican Peso)" },
                { key: "MXV", value: "MXV (Mexican Unidad de Inversion (UDI) (Funds code))" },
                { key: "MYR", value: "MYR (Malaysian Ringgit)" },
                { key: "MZN", value: "MZN (Metical)" },
                { key: "NAD", value: "NAD (Namibian Dollar)" },
                { key: "NGN", value: "NGN (Naira)" },
                { key: "NIO", value: "NIO (Cordoba Oro)" },
                { key: "NOK", value: "NOK (Norwegian Krone)" },
                { key: "NPR", value: "NPR (Nepalese Rupee)" },
                { key: "NZD", value: "NZD (New Zealand Dollar)" },
                { key: "OMR", value: "OMR (Rial Omani)" },
                { key: "PAB", value: "PAB (Balboa)" },
                { key: "PEN", value: "PEN (Nuevo Sol)" },
                { key: "PGK", value: "PGK (Kina)" },
                { key: "PHP", value: "PHP (Philippine Peso)" },
                { key: "PKR", value: "PKR (Pakistan Rupee)" },
                { key: "PLN", value: "PLN (Zloty)" },
                { key: "PYG", value: "PYG (Guarani)" },
                { key: "QAR", value: "QAR (Qatari Rial)" },
                { key: "RON", value: "RON (Romanian New Leu)" },
                { key: "RSD", value: "RSD (Serbian Dinar)" },
                { key: "RUB", value: "RUB (Russian Ruble)" },
                { key: "RWF", value: "RWF (Rwanda Franc)" },
                { key: "SAR", value: "SAR (Saudi Riyal)" },
                { key: "SBD", value: "SBD (Solomon Islands Dollar)" },
                { key: "SCR", value: "SCR (Seychelles Rupee)" },
                { key: "SDG", value: "SDG (Sudanese Pound)" },
                { key: "SSP", value: "SSP (South Sudanese Pound)" },
                { key: "SEK", value: "SEK (Swedish Krona)" },
                { key: "SGD", value: "SGD (Singapore Dollar)" },
                { key: "SHP", value: "SHP (Saint Helena Pound)" },
                { key: "SKK", value: "SKK (Slovak Koruna)" },
                { key: "SLL", value: "SLL (Leone)" },
                { key: "SOS", value: "SOS (Somali Shilling)" },
                { key: "SRD", value: "SRD (Surinam Dollar)" },
                { key: "STD", value: "STD (Dobra)" },
                { key: "SYP", value: "SYP (Syrian Pound)" },
                { key: "SZL", value: "SZL (Lilangeni)" },
                { key: "THB", value: "THB (Baht)" },
                { key: "TJS", value: "TJS (Somoni)" },
                { key: "TMM", value: "TMM (Manat)" },
                { key: "TND", value: "TND (Tunisian Dinar)" },
                { key: "TOP", value: "TOP (Pa'anga)" },
                { key: "TRY", value: "TRY (New Turkish Lira)" },
                { key: "TTD", value: "TTD (Trinidad and Tobago Dollar)" },
                { key: "TWD", value: "TWD (New Taiwan Dollar)" },
                { key: "TZS", value: "TZS (Tanzanian Shilling)" },
                { key: "UAH", value: "UAH (Hryvnia)" },
                { key: "UGX", value: "UGX (Uganda Shilling)" },
                { key: "USD", value: "USD (US Dollar)" },
                { key: "USN", value: "USN (USN)" },
                { key: "USS", value: "USS (USS)" },
                { key: "UYU", value: "UYU (Peso Uruguayo)" },
                { key: "UZS", value: "UZS (Uzbekistan Som)" },
                { key: "VEB", value: "VEB (Venezuelan bolívar)" },
                { key: "VND", value: "VND (Vietnamese đồng)" },
                { key: "VUV", value: "VUV (Vatu)" },
                { key: "WST", value: "WST (Samoan Tala)" },
                { key: "XAF", value: "XAF (CFA(Franc BEAC)" },
                { key: "XAG", value: "XAG (Silver (one Troy ounce))" },
                { key: "XAU", value: "XAU (Gold (one Troy ounce))" },
                { key: "XBA", value: "XBA (European Composite Unit (EURCO) (Bonds market unit))" },
                { key: "XBB", value: "XBB (European Monetary Unit (E.M.U.-6) (Bonds market unit))" },
                { key: "XBC", value: "XBC (European Unit of Account 9 (E.U.A.-9) (Bonds market unit))" },
                { key: "XBD", value: "XBD (European Unit of Account 17 (E.U.A.-17) (Bonds market unit))" },
                { key: "XCD", value: "XCD (East Caribbean Dollar)" },
                { key: "XDR", value: "XDR (Special Drawing Rights)" },
                { key: "XFO", value: "XFO (Gold franc (special settlement currency))" },
                { key: "XFU", value: "XFU (UIC franc (special settlement currency))" },
                { key: "XOF", value: "XOF (CFA Franc BCEAO)" },
                { key: "XPD", value: "XPD (Palladium (one Troy ounce))" },
                { key: "XPF", value: "XPF (CFP franc)" },
                { key: "XPT", value: "XPT (Platinum (one Troy ounce))" },
                { key: "XTS", value: "XTS (Code reserved for testing purposes)" },
                { key: "XXX", value: "XXX (No currency)" },
                { key: "YER", value: "YER (Yemeni Rial)" },
                { key: "ZAR", value: "ZAR (South African Rand)" },
                { key: "ZMK", value: "ZMK (Kwacha)" },
                { key: "ZWD", value: "ZWD (Zimbabwe Dollar)" }

            ]
        }
    }

    public getTabellatiMapEn(): IDictionary<any> {
        return {
            'paesi': [
                { key: "AD", value: "Andorra" },
                { key: "AE", value: "United Arab Emirates" },
                { key: "AF", value: "Afghanistan" },
                { key: "AG", value: "Antigua and Barbuda" },
                { key: "AI", value: "Anguilla" },
                { key: "AL", value: "Albania" },
                { key: "AM", value: "Armenia" },
                { key: "AO", value: "Angola" },
                { key: "AQ", value: "Antarctica" },
                { key: "AR", value: "Argentina" },
                { key: "AS", value: "American Samoa" },
                { key: "AT", value: "Austria" },
                { key: "AU", value: "Australia" },
                { key: "AW", value: "Aruba" },
                { key: "AX", value: "Åland Islands" },
                { key: "AZ", value: "Azerbaijan" },
                { key: "BA", value: "Bosnia and Herzegovina" },
                { key: "BB", value: "Barbados" },
                { key: "BD", value: "Bangladesh" },
                { key: "BE", value: "Belgium" },
                { key: "BF", value: "Burkina Faso" },
                { key: "BG", value: "Bulgaria" },
                { key: "BH", value: "Bahrain" },
                { key: "BI", value: "Burundi" },
                { key: "BJ", value: "Benin" },
                { key: "BL", value: "Saint Barthélemy" },
                { key: "BM", value: "Bermuda" },
                { key: "BN", value: "Brunei Darussalam" },
                { key: "BO", value: "Bolivia, Plurinational State of" },
                { key: "BQ", value: "Bonaire, Sint Eustatius and Saba" },
                { key: "BR", value: "Brazil" },
                { key: "BS", value: "Bahamas" },
                { key: "BT", value: "Bhutan" },
                { key: "BV", value: "Bouvet Island" },
                { key: "BW", value: "Botswana" },
                { key: "BY", value: "Belarus" },
                { key: "BZ", value: "Belize" },
                { key: "CA", value: "Canada" },
                { key: "CC", value: "Cocos (Keeling) Islands" },
                { key: "CD", value: "Congo, the Democratic Republic of the" },
                { key: "CF", value: "Central African Republic" },
                { key: "CG", value: "Congo" },
                { key: "CH", value: "Switzerland" },
                { key: "CI", value: "Côte d'Ivoire" },
                { key: "CK", value: "Cook Islands" },
                { key: "CL", value: "Chile" },
                { key: "CM", value: "Cameroon" },
                { key: "CN", value: "China" },
                { key: "CO", value: "Colombia" },
                { key: "CR", value: "Costa Rica" },
                { key: "CU", value: "Cuba" },
                { key: "CV", value: "Cabo Verde" },
                { key: "CW", value: "Curaçao" },
                { key: "CX", value: "Christmas Island" },
                { key: "CY", value: "Cyprus" },
                { key: "CZ", value: "Czech Republic" },
                { key: "DE", value: "Germany" },
                { key: "DJ", value: "Djibouti" },
                { key: "DK", value: "Denmark" },
                { key: "DM", value: "Dominica" },
                { key: "DO", value: "Dominican Republic" },
                { key: "DZ", value: "Algeria" },
                { key: "EC", value: "Ecuador" },
                { key: "EE", value: "Estonia" },
                { key: "EG", value: "Egypt" },
                { key: "EH", value: "Western Sahara" },
                { key: "ER", value: "Eritrea" },
                { key: "ES", value: "Spain" },
                { key: "ET", value: "Ethiopia" },
                { key: "FI", value: "Finland" },
                { key: "FJ", value: "Fiji" },
                { key: "FK", value: "Falkland Islands (Malvinas)" },
                { key: "FM", value: "Micronesia, Federated States of" },
                { key: "FO", value: "Faroe Islands" },
                { key: "FR", value: "France" },
                { key: "GA", value: "Gabon" },
                { key: "GB", value: "United Kingdom of Great Britain and Northern Ireland" },
                { key: "GD", value: "Grenada" },
                { key: "GE", value: "Georgia" },
                { key: "GF", value: "French Guiana" },
                { key: "GG", value: "Guernsey" },
                { key: "GH", value: "Ghana" },
                { key: "GI", value: "Gibraltar" },
                { key: "GL", value: "Greenland" },
                { key: "GM", value: "Gambia" },
                { key: "GN", value: "Guinea" },
                { key: "GP", value: "Guadeloupe" },
                { key: "GQ", value: "Equatorial Guinea" },
                { key: "GR", value: "Greece" },
                { key: "GS", value: "South Georgia and the South Sandwich Islands" },
                { key: "GT", value: "Guatemala" },
                { key: "GU", value: "Guam" },
                { key: "GW", value: "Guinea-Bissau" },
                { key: "GY", value: "Guyana" },
                { key: "HK", value: "Hong Kong" },
                { key: "HM", value: "Heard Island and McDonald Islands" },
                { key: "HN", value: "Honduras" },
                { key: "HR", value: "Croatia" },
                { key: "HT", value: "Haiti" },
                { key: "HU", value: "Hungary" },
                { key: "ID", value: "Indonesia" },
                { key: "IE", value: "Ireland" },
                { key: "IL", value: "Israel" },
                { key: "IM", value: "Isle of Man" },
                { key: "IN", value: "India" },
                { key: "IO", value: "British Indian Ocean Territory" },
                { key: "IQ", value: "Iraq" },
                { key: "IR", value: "Iran, Islamic Republic of" },
                { key: "IS", value: "Iceland" },
                { key: "IT", value: "Italy" },
                { key: "JE", value: "Jersey" },
                { key: "JM", value: "Jamaica" },
                { key: "JO", value: "Jordan" },
                { key: "JP", value: "Japan" },
                { key: "KE", value: "Kenya" },
                { key: "KG", value: "Kyrgyzstan" },
                { key: "KH", value: "Cambodia" },
                { key: "KI", value: "Kiribati" },
                { key: "KM", value: "Comoros" },
                { key: "KN", value: "Saint Kitts and Nevis" },
                { key: "KP", value: "Korea, Democratic People's Republic of" },
                { key: "KR", value: "Korea, Republic of" },
                { key: "KW", value: "Kuwait" },
                { key: "KY", value: "Cayman Islands" },
                { key: "KZ", value: "Kazakhstan" },
                { key: "LA", value: "Lao People's Democratic Republic" },
                { key: "LB", value: "Lebanon" },
                { key: "LC", value: "Saint Lucia" },
                { key: "LI", value: "Liechtenstein" },
                { key: "LK", value: "Sri Lanka" },
                { key: "LR", value: "Liberia" },
                { key: "LS", value: "Lesotho" },
                { key: "LT", value: "Lithuania" },
                { key: "LU", value: "Luxembourg" },
                { key: "LV", value: "Latvia" },
                { key: "LY", value: "Libya" },
                { key: "MA", value: "Morocco" },
                { key: "MC", value: "Monaco" },
                { key: "MD", value: "Moldova, Republic of" },
                { key: "ME", value: "Montenegro" },
                { key: "MF", value: "Saint Martin (French part)" },
                { key: "MG", value: "Madagascar" },
                { key: "MH", value: "Marshall Islands" },
                { key: "MK", value: "Macedonia, the former Yugoslav Republic of" },
                { key: "ML", value: "Mali" },
                { key: "MM", value: "Myanmar" },
                { key: "MN", value: "Mongolia" },
                { key: "MO", value: "Macao" },
                { key: "MP", value: "Northern Mariana Islands" },
                { key: "MQ", value: "Martinique" },
                { key: "MR", value: "Mauritania" },
                { key: "MS", value: "Montserrat" },
                { key: "MT", value: "Malta" },
                { key: "MU", value: "Mauritius" },
                { key: "MV", value: "Maldives" },
                { key: "MW", value: "Malawi" },
                { key: "MX", value: "Mexico" },
                { key: "MY", value: "Malaysia" },
                { key: "MZ", value: "Mozambique" },
                { key: "NA", value: "Namibia" },
                { key: "NC", value: "New Caledonia" },
                { key: "NE", value: "Niger" },
                { key: "NF", value: "Norfolk Island" },
                { key: "NG", value: "Nigeria" },
                { key: "NI", value: "Nicaragua" },
                { key: "NL", value: "Netherlands" },
                { key: "NO", value: "Norway" },
                { key: "NP", value: "Nepal" },
                { key: "NR", value: "Nauru" },
                { key: "NU", value: "Niue" },
                { key: "NZ", value: "New Zealand" },
                { key: "OM", value: "Oman" },
                { key: "PA", value: "Panama" },
                { key: "PE", value: "Peru" },
                { key: "PF", value: "French Polynesia" },
                { key: "PG", value: "Papua New Guinea" },
                { key: "PH", value: "Philippines" },
                { key: "PK", value: "Pakistan" },
                { key: "PL", value: "Poland" },
                { key: "PM", value: "Saint Pierre and Miquelon" },
                { key: "PN", value: "Pitcairn" },
                { key: "PR", value: "Puerto Rico" },
                { key: "PS", value: "Palestine, State of" },
                { key: "PT", value: "Portugal" },
                { key: "PW", value: "Palau" },
                { key: "PY", value: "Paraguay" },
                { key: "QA", value: "Qatar" },
                { key: "RE", value: "Réunion" },
                { key: "RO", value: "Romania" },
                { key: "RS", value: "Serbia" },
                { key: "RU", value: "Russian Federation" },
                { key: "RW", value: "Rwanda" },
                { key: "SA", value: "Saudi Arabia" },
                { key: "SB", value: "Solomon Islands" },
                { key: "SC", value: "Seychelles" },
                { key: "SD", value: "Sudan" },
                { key: "SE", value: "Sweden" },
                { key: "SG", value: "Singapore" },
                { key: "SH", value: "Saint Helena, Ascension and Tristan da Cunha" },
                { key: "SI", value: "Slovenia" },
                { key: "SJ", value: "Svalbard and Jan Mayen" },
                { key: "SK", value: "Slovakia" },
                { key: "SL", value: "Sierra Leone" },
                { key: "SM", value: "San Marino" },
                { key: "SN", value: "Senegal" },
                { key: "SO", value: "Somalia" },
                { key: "SR", value: "Suriname" },
                { key: "SS", value: "South Sudan" },
                { key: "ST", value: "Sao Tome and Principe" },
                { key: "SV", value: "El Salvador" },
                { key: "SX", value: "Sint Maarten (Dutch part)" },
                { key: "SY", value: "Syrian Arab Republic" },
                { key: "SZ", value: "Swaziland" },
                { key: "TC", value: "Turks and Caicos Islands" },
                { key: "TD", value: "Chad" },
                { key: "TF", value: "French Southern Territories" },
                { key: "TG", value: "Togo" },
                { key: "TH", value: "Thailand" },
                { key: "TJ", value: "Tajikistan" },
                { key: "TK", value: "Tokelau" },
                { key: "TL", value: "Timor-Leste" },
                { key: "TM", value: "Turkmenistan" },
                { key: "TN", value: "Tunisia" },
                { key: "TO", value: "Tonga" },
                { key: "TR", value: "Turkey" },
                { key: "TT", value: "Trinidad and Tobago" },
                { key: "TV", value: "Tuvalu" },
                { key: "TW", value: "Taiwan, Province of China" },
                { key: "TZ", value: "Tanzania, United Republic of" },
                { key: "UA", value: "Ukraine" },
                { key: "UG", value: "Uganda" },
                { key: "UM", value: "United States Minor Outlying Islands" },
                { key: "US", value: "United States of America" },
                { key: "UY", value: "Uruguay" },
                { key: "UZ", value: "Uzbekistan" },
                { key: "VA", value: "Holy See" },
                { key: "VC", value: "Saint Vincent and the Grenadines" },
                { key: "VE", value: "Venezuela, Bolivarian Republic of" },
                { key: "VG", value: "Virgin Islands, British" },
                { key: "VI", value: "Virgin Islands, U.S." },
                { key: "VN", value: "Viet Nam" },
                { key: "VU", value: "Vanuatu" },
                { key: "WF", value: "Wallis and Futuna" },
                { key: "WS", value: "Samoa" },
                { key: "XK", value: "Kosovo" },
                { key: "YE", value: "Yemen" },
                { key: "YT", value: "Mayotte" },
                { key: "ZA", value: "South Africa" },
                { key: "ZM", value: "Zambia" },
                { key: "ZW", value: "Zimbabwe" }

            ],
            "sino": [
                { key: "true", value: this.translateService.instant('COMBOBOX.SI') },
                { key: "false", value: this.translateService.instant('COMBOBOX.NO') }
            ],
            "financialRatioType": [
                { key: "R11", value: "Assets to Equity ratio" },
                { key: "R12", value: "Liabilities to Equity ratio " },
                { key: "R13", value: "Current assets/Total assets " },
                { key: "R14", value: "Other financial assets and cash and bank/ Total assets" },
                { key: "R15", value: "Non-current debt/ Total assets " },
                { key: "R16", value: "Current debt/Total assets " },
                { key: "R21", value: "Financial income net of charges other than interest/EBITDA" },
                { key: "R22", value: "EBITDA/Interest on financial debt" },
                { key: "R23", value: "Interest burden" },
                { key: "R24", value: "Interest and similar charges/Net turnove" },
                { key: "R25", value: "Interest and similar charges/Gross operating profit" },
                { key: "R26", value: "Net financial income/Gross operating profit" },
                { key: "R27", value: "Gross operating profit/Total net debt" },
                { key: "R31", value: "Gross value added/Net turnove" },
                { key: "R32", value: "Gross operating profit/Net turnover (ROS)" },
                { key: "R33", value: "EBITDA/Net turnove" },
                { key: "R34", value: "Net operating profit/Net turnover" },
                { key: "R35", value: "EBIT/Net turnover" },
                { key: "R36", value: "EBT/Net turnover" },
                { key: "R37", value: "Net financial income/Net turnover" },
                { key: "R38", value: "Return on equity" },
                { key: "R39", value: "Net operating profit/Total assets" },
                { key: "R310", value: "Profit or loss for the year before taxes/Equity" },
                { key: "R41", value: "Asset turnover ratio" },
                { key: "R42", value: "Employee expenses/Gross value added" },
                { key: "R51", value: "Inventories/Net turnover" },
                { key: "R52", value: "Trade receivables/Net turnover" },
                { key: "R53", value: "Trade payables/Net turnover" },
                { key: "R54", value: "Operating working capital/Net turnover" }
            ],
            "IndustryClassificationCode": [
                { key: "MICRO", value: "Micro enterprise" },
                { key: "SMALL", value: "small enterprise" },
                { key: "MEDIUM", value: "medium enterprise" }
            ],
            "tipoProcedura": [
                /*{key:"NS" , value:"Non specificato"},
                {key:"PA" , value:"Procedura aperta"},
                {key:"PR" , value:"Procedura ristretta"},
                {key:"PCN" , value:"Procedura competitiva con negoziazione"},
                {key:"DC" , value:"Dialogo competitivo"},
                {key:"PI" , value:"Partenariato per l'innovazione"}*/
                { key: "PRIOR", value: "Prior information or periodic indicative notice" },
                { key: "OPEN", value: "Open procedure" },
                { key: "RESTRICTED", value: "Restricted procedure" },
                { key: "RESTRICTED_ACCELERATED", value: "Accelerated restricted procedure" },
                { key: "NEGOTIATED", value: "Negotiated procedure" },
                { key: "OPEN_RECUR", value: "Open procedure with recurring quantities" },
                { key: "NEGOTIATED_ACCELERATED", value: "Accelerated negotiated procedure" },
                { key: "AWARD", value: "Contract awards" },
                { key: "INFO", value: "General information" },
                { key: "AWARD_DIRECT", value: "Direct Award" },
                { key: "COMP_NEGOTIATION", value: "Competitive procedure with negotiation" },
                { key: "COMP_DIALOGUE", value: "Competitive dialogue" },
                { key: "DESIGN_CONTEST", value: "Design contest" },
                { key: "CONCESSION", value: "Concession award procedure" },
                { key: "CONCESSION_WO_PUB", value: "Concession award without prior concession notice" },
                { key: "INNOVATION", value: "Innovation partnership" },
                { key: "AMI", value: "Call for expressions of interest" },
                { key: "NOT_SPECIFIED", value: "Not specified" },
                { key: "QUAL", value: "Qualification system" },
                { key: "CONTESTS_RESULT", value: "Results of design contests" },
                { key: "NEGOTIATED_WO_CALL", value: "Negotiated without a prior call for competition" },
                { key: "AWARD_WO_PUB", value: "Contract award without prior publication" },
                { key: "OTHER", value: "Other" },
                { key: "NOT_APPLICABLE", value: "Not applicable" },
                { key: "LOV", value: "Negotiated Procedure for low value contracts" },
                { key: "VDL", value: "Vendor's list" }
            ],
            "ruoloOperatoreEconomico": [
                /*DEPRECATO { key: "SCLE", value: "Sole contractor / Lead entity" },*/
                { key: "GM", value: "Group member" },
                { key: "OERON", value: "Other entity (relied upon)" },
                { key: "OENRON", value: "Other entity (not relied upon)" },
                { key: "SC", value: "Sole entity" },
                { key: "LE", value: "The leader of a Consortium, Joint Venture or another type of group." }
            ],
            "bidType": [
                { key: "LOT_ALL", value: "Submission for all lots" },
                { key: "LOT_ONE", value: "Submission for one lot only" },
                { key: "LOT_ONE_MORE", value: "Submission for one or more lots" },
                { key: "OTHER", value: "Others" },
                { key: "NOT_APPLICABLE", value: "Not applicable" },
                { key: "NOT_SPECIFIED", value: "Not specified" }
            ],
            "DocRefContentType": [
                { key: "TED_CN", value: "Contract Notice published in TeD (Official Journal of the European Publications Office)" },
                { key: "ESPD_REQUEST", value: "European Single Procurement Document Request issued by a Contracting Authority" },
                { key: "TECC016", value: "Letter of Intent " },
                { key: "TECC017", value: "Status of the legal entity " },
                { key: "TECC018", value: "Notice of appointment of the persons authorised to represent the tenderer" },
                { key: "TECC019", value: "VAT registration document" },
                { key: "TECC020", value: "Identity document " },
                { key: "TECC021", value: "Reason for VAT exemption " },
                { key: "TECC022", value: "Subcontracting justification " },
                { key: "TECC024", value: "Power of Attorney " },
                { key: "Other", value: "Other type of reference to a document" },
                { key: "NOJCN", value: "Contract Notice (CN) published on a National Government Official Journal" },
                { key: "ROJCN", value: "Contract Notice (CN) published on a Regional Government Official Journal" },
                { key: "LOJCN", value: "Contract Notice (CN) published on a Local Government Official Journal" },
                { key: "NOJPIN", value: "Prior Information Notice (PIN) published on a National Government Official Journal" },
                { key: "ROJPIN", value: "Prior Information Notice (PIN) published on a Regional Government Official Journal" },
                { key: "LOJPIN", value: "Prior Information Notice (PIN) published on a Local Government Official Journal" },
                { key: "NOJCAN", value: "Contract Award Notice (CAN) published on a National Government Official Journal" },
                { key: "ROJCAN", value: "Contract Award Notice (CAN) published on a Regional Government Official Journal" },
                { key: "LOJCAN", value: "Contract Award Notice (CAN) published on a Local Government Official Journal" }
            ],
            "projectType": [
                { key: "WORKS", value: "Works" },
                { key: "SUPPLIES", value: "Supplies" },
                { key: "COMBINED", value: "Combined" },
                { key: "SERVICES", value: "Services" },
                { key: "OTHER", value: "Others" },
                { key: "NOT_APPLICABLE", value: "Non applicabile" },
                { key: "NOT_SPECIFIED", value: "Non specificato" },
                { key: "CON_PUBLIC_WORKS", value: "Public Works Concession" },
                { key: "CON_SERVICE", value: "Service Concession" },
            ],
            "typeOfRequirements": [
                { key: "RADIO_BUTTON_TRUE", value: "Economic and financial requirements" },
                { key: "RADIO_BUTTON_FALSE", value: "Evaluation requirements" },
            ],
            "tipoMoneta": [
                { key: "AED", value: "AED (United Arab Emirates dirham)" },
                { key: "AFN", value: "AFN (Afghani)" },
                { key: "ALL", value: "ALL (Lek)" },
                { key: "AMD", value: "AMD (Armenian Dram)" },
                { key: "ANG", value: "ANG (Netherlands Antillian Guilder)" },
                { key: "AOA", value: "AOA (Kwanza)" },
                { key: "ARS", value: "ARS (Argentine Peso)" },
                { key: "AUD", value: "AUD (Australian Dollar)" },
                { key: "AWG", value: "AWG (Aruban Guilder)" },
                { key: "AZN", value: "AZN (Azerbaijanian Manat)" },
                { key: "BAM", value: "BAM (Convertible Marks)" },
                { key: "BBD", value: "BBD (Barbados Dollar)" },
                { key: "BDT", value: "BDT (Bangladeshi Taka)" },
                { key: "BGN", value: "BGN (Bulgarian Lev)" },
                { key: "BHD", value: "BHD (Bahraini Dinar)" },
                { key: "BIF", value: "BIF (Burundian Franc)" },
                { key: "BMD", value: "BMD (Bermudian Dollar (customarily known as Bermuda Dollar))" },
                { key: "BND", value: "BND (Brunei Dollar)" },
                { key: "BOB", value: "BOB (Boliviano)" },
                { key: "BOV", value: "BOV (Bolivian Mvdol (Funds code))" },
                { key: "BRL", value: "BRL (Brazilian Real)" },
                { key: "BSD", value: "BSD (Bahamian Dollar)" },
                { key: "BTN", value: "BTN (Ngultrum)" },
                { key: "BWP", value: "BWP (Pula)" },
                { key: "BYR", value: "BYR (Belarussian Ruble)" },
                { key: "BZD", value: "BZD (Belize Dollar)" },
                { key: "CAD", value: "CAD (Canadian Dollar)" },
                { key: "CDF", value: "CDF (Franc Congolais)" },
                { key: "CHE", value: "CHE (WIR(Euro (complementary currency))" },
                { key: "CHF", value: "CHF (Swiss Franc)" },
                { key: "CHW", value: "CHW (WIR Franc (complementary currency))" },
                { key: "CLF", value: "CLF (Unidades de formento (Funds code))" },
                { key: "CLP", value: "CLP (Chilean Peso)" },
                { key: "CNY", value: "CNY (Yuan Renminbi)" },
                { key: "COP", value: "COP (Colombian Peso)" },
                { key: "COU", value: "COU (Unidad de Valor Real)" },
                { key: "CRC", value: "CRC (Costa Rican Colon)" },
                { key: "CUP", value: "CUP (Cuban Peso)" },
                { key: "CVE", value: "CVE (Cape Verde Escudo)" },
                { key: "CZK", value: "CZK (Czech Koruna)" },
                { key: "DJF", value: "DJF (Djibouti Franc)" },
                { key: "DKK", value: "DKK (Danish Krone)" },
                { key: "DOP", value: "DOP (Dominican Peso)" },
                { key: "DZD", value: "DZD (Algerian Dinar)" },
                { key: "EEK", value: "EEK (Kroon)" },
                { key: "EGP", value: "EGP (Egyptian Pound)" },
                { key: "ERN", value: "ERN (Nakfa)" },
                { key: "ETB", value: "ETB (Ethiopian Birr)" },
                { key: "EUR", value: "EUR (Euro)" },
                { key: "FJD", value: "FJD (Fiji Dollar)" },
                { key: "FKP", value: "FKP (Falkland Islands Pound)" },
                { key: "GBP", value: "GBP (Pound Sterling)" },
                { key: "GEL", value: "GEL (Lari)" },
                { key: "GHS", value: "GHS (Cedi)" },
                { key: "GIP", value: "GIP (Gibraltar pound)" },
                { key: "GMD", value: "GMD (Dalasi)" },
                { key: "GNF", value: "GNF (Guinea Franc)" },
                { key: "GTQ", value: "GTQ (Quetzal)" },
                { key: "GYD", value: "GYD (Guyana Dollar)" },
                { key: "HKD", value: "HKD (Hong Kong Dollar)" },
                { key: "HNL", value: "HNL (Lempira)" },
                { key: "HRK", value: "HRK (Croatian Kuna)" },
                { key: "HTG", value: "HTG (Haiti Gourde)" },
                { key: "HUF", value: "HUF (Forint)" },
                { key: "IDR", value: "IDR (Rupiah)" },
                { key: "ILS", value: "ILS (New Israeli Shekel)" },
                { key: "INR", value: "INR (Indian Rupee)" },
                { key: "IQD", value: "IQD (Iraqi Dinar)" },
                { key: "IRR", value: "IRR (Iranian Rial)" },
                { key: "ISK", value: "ISK (Iceland Krona)" },
                { key: "JMD", value: "JMD (Jamaican Dollar)" },
                { key: "JOD", value: "JOD (Jordanian Dinar)" },
                { key: "JPY", value: "JPY (Japanese yen)" },
                { key: "KES", value: "KES (Kenyan Shilling)" },
                { key: "KGS", value: "KGS (Som)" },
                { key: "KHR", value: "KHR (Riel)" },
                { key: "KMF", value: "KMF (Comoro Franc)" },
                { key: "KPW", value: "KPW (North Korean Won)" },
                { key: "KRW", value: "KRW (South Korean Won)" },
                { key: "KWD", value: "KWD (Kuwaiti Dinar)" },
                { key: "KYD", value: "KYD (Cayman Islands Dollar)" },
                { key: "KZT", value: "KZT (Tenge)" },
                { key: "LAK", value: "LAK (Kip)" },
                { key: "LBP", value: "LBP (Lebanese Pound)" },
                { key: "LKR", value: "LKR (Sri Lanka Rupee)" },
                { key: "LRD", value: "LRD (Liberian Dollar)" },
                { key: "LSL", value: "LSL (Loti)" },
                { key: "LTL", value: "LTL (Lithuanian Litas)" },
                { key: "LVL", value: "LVL (Latvian Lats)" },
                { key: "LYD", value: "LYD (Libyan Dinar)" },
                { key: "MAD", value: "MAD (Moroccan Dirham)" },
                { key: "MDL", value: "MDL (Moldovan Leu)" },
                { key: "MGA", value: "MGA (Malagasy Ariary)" },
                { key: "MKD", value: "MKD (Denar)" },
                { key: "MMK", value: "MMK (Kyat)" },
                { key: "MNT", value: "MNT (Tugrik)" },
                { key: "MOP", value: "MOP (Pataca)" },
                { key: "MRO", value: "MRO (Ouguiya)" },
                { key: "MTL", value: "MTL (Maltese Lira)" },
                { key: "MUR", value: "MUR (Mauritius Rupee)" },
                { key: "MVR", value: "MVR (Rufiyaa)" },
                { key: "MWK", value: "MWK (Kwacha)" },
                { key: "MXN", value: "MXN (Mexican Peso)" },
                { key: "MXV", value: "MXV (Mexican Unidad de Inversion (UDI) (Funds code))" },
                { key: "MYR", value: "MYR (Malaysian Ringgit)" },
                { key: "MZN", value: "MZN (Metical)" },
                { key: "NAD", value: "NAD (Namibian Dollar)" },
                { key: "NGN", value: "NGN (Naira)" },
                { key: "NIO", value: "NIO (Cordoba Oro)" },
                { key: "NOK", value: "NOK (Norwegian Krone)" },
                { key: "NPR", value: "NPR (Nepalese Rupee)" },
                { key: "NZD", value: "NZD (New Zealand Dollar)" },
                { key: "OMR", value: "OMR (Rial Omani)" },
                { key: "PAB", value: "PAB (Balboa)" },
                { key: "PEN", value: "PEN (Nuevo Sol)" },
                { key: "PGK", value: "PGK (Kina)" },
                { key: "PHP", value: "PHP (Philippine Peso)" },
                { key: "PKR", value: "PKR (Pakistan Rupee)" },
                { key: "PLN", value: "PLN (Zloty)" },
                { key: "PYG", value: "PYG (Guarani)" },
                { key: "QAR", value: "QAR (Qatari Rial)" },
                { key: "RON", value: "RON (Romanian New Leu)" },
                { key: "RSD", value: "RSD (Serbian Dinar)" },
                { key: "RUB", value: "RUB (Russian Ruble)" },
                { key: "RWF", value: "RWF (Rwanda Franc)" },
                { key: "SAR", value: "SAR (Saudi Riyal)" },
                { key: "SBD", value: "SBD (Solomon Islands Dollar)" },
                { key: "SCR", value: "SCR (Seychelles Rupee)" },
                { key: "SDG", value: "SDG (Sudanese Pound)" },
                { key: "SSP", value: "SSP (South Sudanese Pound)" },
                { key: "SEK", value: "SEK (Swedish Krona)" },
                { key: "SGD", value: "SGD (Singapore Dollar)" },
                { key: "SHP", value: "SHP (Saint Helena Pound)" },
                { key: "SKK", value: "SKK (Slovak Koruna)" },
                { key: "SLL", value: "SLL (Leone)" },
                { key: "SOS", value: "SOS (Somali Shilling)" },
                { key: "SRD", value: "SRD (Surinam Dollar)" },
                { key: "STD", value: "STD (Dobra)" },
                { key: "SYP", value: "SYP (Syrian Pound)" },
                { key: "SZL", value: "SZL (Lilangeni)" },
                { key: "THB", value: "THB (Baht)" },
                { key: "TJS", value: "TJS (Somoni)" },
                { key: "TMM", value: "TMM (Manat)" },
                { key: "TND", value: "TND (Tunisian Dinar)" },
                { key: "TOP", value: "TOP (Pa'anga)" },
                { key: "TRY", value: "TRY (New Turkish Lira)" },
                { key: "TTD", value: "TTD (Trinidad and Tobago Dollar)" },
                { key: "TWD", value: "TWD (New Taiwan Dollar)" },
                { key: "TZS", value: "TZS (Tanzanian Shilling)" },
                { key: "UAH", value: "UAH (Hryvnia)" },
                { key: "UGX", value: "UGX (Uganda Shilling)" },
                { key: "USD", value: "USD (US Dollar)" },
                { key: "USN", value: "USN (USN)" },
                { key: "USS", value: "USS (USS)" },
                { key: "UYU", value: "UYU (Peso Uruguayo)" },
                { key: "UZS", value: "UZS (Uzbekistan Som)" },
                { key: "VEB", value: "VEB (Venezuelan bolívar)" },
                { key: "VND", value: "VND (Vietnamese đồng)" },
                { key: "VUV", value: "VUV (Vatu)" },
                { key: "WST", value: "WST (Samoan Tala)" },
                { key: "XAF", value: "XAF (CFA(Franc BEAC)" },
                { key: "XAG", value: "XAG (Silver (one Troy ounce))" },
                { key: "XAU", value: "XAU (Gold (one Troy ounce))" },
                { key: "XBA", value: "XBA (European Composite Unit (EURCO) (Bonds market unit))" },
                { key: "XBB", value: "XBB (European Monetary Unit (E.M.U.-6) (Bonds market unit))" },
                { key: "XBC", value: "XBC (European Unit of Account 9 (E.U.A.-9) (Bonds market unit))" },
                { key: "XBD", value: "XBD (European Unit of Account 17 (E.U.A.-17) (Bonds market unit))" },
                { key: "XCD", value: "XCD (East Caribbean Dollar)" },
                { key: "XDR", value: "XDR (Special Drawing Rights)" },
                { key: "XFO", value: "XFO (Gold franc (special settlement currency))" },
                { key: "XFU", value: "XFU (UIC franc (special settlement currency))" },
                { key: "XOF", value: "XOF (CFA Franc BCEAO)" },
                { key: "XPD", value: "XPD (Palladium (one Troy ounce))" },
                { key: "XPF", value: "XPF (CFP franc)" },
                { key: "XPT", value: "XPT (Platinum (one Troy ounce))" },
                { key: "XTS", value: "XTS (Code reserved for testing purposes)" },
                { key: "XXX", value: "XXX (No currency)" },
                { key: "YER", value: "YER (Yemeni Rial)" },
                { key: "ZAR", value: "ZAR (South African Rand)" },
                { key: "ZMK", value: "ZMK (Kwacha)" },
                { key: "ZWD", value: "ZWD (Zimbabwe Dollar)" }

            ]
        }
    }


}
